# -*- coding: utf-8 -*-
"""Contenu Tache 2 — Expression orale Novembre 2025 (texte source exact)."""


def sub(title, prompt, correction, icon="bx bx-message-detail"):
    return {
        "title": title,
        "prompt": prompt.strip(),
        "correction": correction.strip(),
        "icon_class": icon,
    }


def part(task_key, part_num, subjects):
    return {
        "task_key": task_key,
        "part_number": part_num,
        "part_title": f"Partie {part_num}",
        "subjects": subjects,
    }


def L(*lines):
    return "\n".join(lines)


TACHE2 = [
    part("tache2", 1, [
        sub(
            "Sujet 1",
            "Je suis votre ami(e). Je pars en vacances et je vous demande de garder mon chat. Vous me posez des questions pour mieux connaître ses habitudes (nourriture, sorties, soins, etc.).",
            L(
                "Comment s'appelle ton chat ?",
                "Il a quel âge ?",
                "Il mange combien de fois par jour ?",
                "Quelle marque ou type de nourriture lui donnes-tu ?",
                "Est-ce qu'il faut lui donner des friandises ?",
                "Où dors-t-il habituellement ?",
                "Est-ce qu'il sort dehors ou il reste à la maison ?",
                "Si oui, il faut lui ouvrir la porte ou il a une chatière ?",
                "Est-ce qu'il aime jouer ? Avec quels jouets ?",
                "Y a-t-il des endroits interdits dans la maison pour lui ?",
                "Que dois-je faire s'il tombe malade ?",
                "Est-ce qu'il a un vétérinaire habituel ?",
                "Il faut nettoyer sa litière combien de fois par jour ?",
                "Est-ce qu'il est sociable avec les autres animaux ?",
                "As-tu des instructions particulières si je dois m'absenter quelques heures ?",
            ),
        ),
        sub(
            "Sujet 2",
            "Je suis votre ami(e). J'organise mon anniversaire sur un bateau. Vous êtes intéressé(e) et vous me posez des questions pour en savoir plus (organisation, prix, invités, etc.).",
            L(
                "C'est toi qui as eu l'idée de fêter ton anniversaire sur un bateau ?",
                "Où se trouve le port de départ ?",
                "Combien de temps dure la fête ?",
                "Combien de personnes seront invitées ?",
                "Est-ce que tout le monde doit payer une participation ?",
                "Quel est le prix par personne ?",
                "Est-ce qu'il y aura un repas servi à bord ?",
                "Quelle est la tenue recommandée ?",
                "Le bateau restera au port ou il naviguera ?",
                "Est-ce qu'il y aura de la musique ou un DJ ?",
                "Peut-on apporter un gâteau ou des boissons ?",
                "Que se passe-t-il en cas de mauvais temps ?",
                "Faut-il réserver à l'avance ?",
                "À quelle heure faut-il arriver ?",
                "Est-ce qu'on peut venir accompagné ?",
            ),
        ),
        sub(
            "Sujet 3",
            "Je suis votre collègue. Je suis membre d'un club de marche. Vous êtes intéressé(e) et vous me posez des questions (lieux, horaires, matériel, etc.).",
            L(
                "Depuis combien de temps tu fais partie de ce club ?",
                "À quelle fréquence vous marchez ?",
                "Quels jours de la semaine avez-vous des sorties ?",
                "Combien de temps durent les marches ?",
                "Quels types de parcours faites-vous ? (ville, montagne, campagne…)",
                "Est-ce qu'il faut un bon niveau physique pour participer ?",
                "Faut-il payer une cotisation annuelle ?",
                "Quel équipement est nécessaire ?",
                "Où se trouve le point de rendez-vous ?",
                "Combien de participants en moyenne par sortie ?",
                "Est-ce que le club organise des événements spéciaux ?",
                "Peut-on venir essayer avant de s'inscrire ?",
                "Que faites-vous en cas de pluie ?",
                "Est-ce qu'il y a des pauses pendant la marche ?",
                "Y a-t-il un encadrement ou un guide ?",
            ),
        ),
        sub(
            "Sujet 4",
            "Je travaille à l'accueil d'un centre culturel. Vous voulez vous informer sur les activités proposées et vous me posez des questions (public concerné, horaires, types d'activités, etc.).",
            L(
                "Quelles activités propose votre centre culturel ?",
                "Y a-t-il des activités pour les enfants ?",
                "Et pour les adultes ?",
                "Quelles sont les activités les plus populaires ?",
                "Quels sont les horaires d'ouverture du centre ?",
                "Est-ce qu'il faut s'inscrire à l'avance ?",
                "Combien coûtent les cours ou ateliers ?",
                "Proposez-vous des cours de musique ou de danse ?",
                "Les activités se déroulent-elles toute l'année ?",
                "Faut-il apporter son propre matériel ?",
                "Est-ce qu'il y a des réductions pour les étudiants ?",
                "Combien de personnes participent en général à un atelier ?",
                "Les professeurs sont-ils des professionnels ?",
                "Est-ce qu'il y a des événements culturels ouverts au public ?",
                "Comment peut-on obtenir le programme complet ?",
            ),
        ),
        sub(
            "Sujet 5",
            "Je travaille à la réception d'un camping. Vous souhaitez louer un emplacement et vous me posez des questions pour préparer votre séjour (services, tarifs, type d'emplacement, etc.).",
            L(
                "Quels types d'emplacements proposez-vous ? (tente, caravane, camping-car…)",
                "Le camping est-il proche de la mer ou d'une rivière ?",
                "Est-ce que les emplacements sont ombragés ?",
                "Quels sont les tarifs par nuit ?",
                "Faut-il réserver à l'avance ?",
                "Est-ce qu'il y a des sanitaires à proximité ?",
                "Proposez-vous un service d'électricité sur les emplacements ?",
                "Y a-t-il une piscine ou des activités sur place ?",
                "Est-ce que les animaux sont acceptés ?",
                "Quels sont les horaires d'arrivée et de départ ?",
                "Y a-t-il un restaurant ou une épicerie dans le camping ?",
                "Peut-on louer du matériel sur place ?",
                "Quelles sont les mesures de sécurité ?",
                "Est-ce que le Wi-Fi est disponible ?",
                "Y a-t-il des animations le soir ?",
            ),
        ),
    ]),
    part("tache2", 2, [
        sub(
            "Sujet 1",
            "Je suis agent immobilier. Vous cherchez à acheter un appartement. Vous avez vu une annonce qui vous intéresse. Vous me posez des questions sur l'appartement (superficie, prix, quartier, etc.).",
            L(
                "Bonjour, l'appartement est-il toujours disponible ?",
                "Quelle est la superficie exacte ?",
                "Dans quel quartier se trouve-t-il ?",
                "Est-ce un quartier calme ?",
                "Le prix est-il négociable ?",
                "Les charges mensuelles sont-elles incluses dans le prix ?",
                "Y a-t-il un balcon ou une terrasse ?",
                "L'appartement est-il ensoleillé ?",
                "À quel étage se situe-t-il ?",
                "Y a-t-il un ascenseur dans l'immeuble ?",
                "Le chauffage est-il individuel ou collectif ?",
                "Les commerces sont-ils proches ?",
                "Est-ce qu'il y a un parking ou un garage ?",
                "Depuis combien de temps l'appartement est-il en vente ?",
                "Quand pourrais-je le visiter ?",
            ),
        ),
        sub(
            "Sujet 2",
            "Je suis parent d'élève. Vous voulez inscrire vos enfants à une activité après l'école. Vous me demandez des informations et des conseils sur les activités proposées dans le quartier (type d'activités, horaires, tarifs, animateurs, etc.).",
            L(
                "Quelles activités proposez-vous pour les enfants après l'école ?",
                "À partir de quel âge peut-on inscrire un enfant ?",
                "Y a-t-il des activités sportives ?",
                "Et des activités artistiques ?",
                "Quels sont les jours et les horaires ?",
                "Combien coûte l'inscription ?",
                "Est-ce qu'il faut payer chaque mois ou à l'année ?",
                "Qui encadre les enfants ?",
                "Les animateurs sont-ils diplômés ?",
                "Combien d'enfants participent par groupe ?",
                "Où se déroulent les activités ?",
                "Est-ce qu'il y a une navette après l'école ?",
                "Peut-on faire un essai avant de s'inscrire ?",
                "Les parents peuvent-ils assister à certaines activités ?",
                "L'inscription se fait en ligne ou sur place ?",
            ),
        ),
        sub(
            "Sujet 3",
            "Je suis votre ami(e). Je suis bénévole dans une association qui distribue des repas aux sans-abris. Vous voulez devenir bénévole. Vous me posez des questions sur l'association (organisation, conditions, emploi du temps, etc.).",
            L(
                "Depuis combien de temps tu fais du bénévolat ?",
                "Comment as-tu connu cette association ?",
                "Quels sont les jours de distribution ?",
                "Où cela se passe-t-il ?",
                "Quelle est la mission principale de l'association ?",
                "Faut-il une formation avant de commencer ?",
                "Est-ce qu'il y a un âge minimum pour participer ?",
                "Combien d'heures faut-il donner par semaine ?",
                "Est-ce que c'est possible de venir seulement le week-end ?",
                "Faut-il s'inscrire à l'avance ?",
                "Combien de bénévoles participent en général ?",
                "Quelle ambiance règne dans le groupe ?",
                "Est-ce que c'est fatigant physiquement ?",
                "Peut-on aider aussi à la préparation des repas ?",
                "L'association propose-t-elle d'autres types d'actions ?",
            ),
        ),
        sub(
            "Sujet 4",
            "Je suis votre ancien(ne) collègue. Je viens de commencer un nouveau travail. Vous souhaitez changer d'emploi. Vous me posez des questions pour avoir des informations sur mon travail et mon entreprise (activités, salaire, collègues, etc.).",
            L(
                "Félicitations pour ton nouveau travail !",
                "Dans quel secteur tu travailles maintenant ?",
                "Quelles sont tes principales tâches ?",
                "Est-ce que c'est un poste à temps plein ?",
                "L'ambiance est-elle bonne dans ton équipe ?",
                "Le salaire est-il plus intéressant que dans notre ancienne entreprise ?",
                "Est-ce que les horaires sont flexibles ?",
                "Tu travailles à distance ou sur place ?",
                "Y a-t-il des possibilités d'évolution dans ton entreprise ?",
                "Le recrutement est-il encore ouvert ?",
                "Quels profils recherchent-ils ?",
                "Quels avantages offre ton entreprise (primes, congés, etc.) ?",
                "Comment s'est passé ton entretien d'embauche ?",
                "Penses-tu que je pourrais postuler aussi ?",
                "Quels conseils me donnerais-tu pour changer de travail ?",
            ),
        ),
        sub(
            "Sujet 5",
            "Nous sommes voisin(e)s. Je vous demande de garder mon enfant le week-end prochain. Vous acceptez. Vous me demandez ce que vous devez faire (horaires, activités, repas, etc.).",
            L(
                "Quel âge a ton enfant ?",
                "À quelle heure dois-je venir le garder ?",
                "Jusqu'à quelle heure dois-je rester ?",
                "Faut-il lui préparer à manger ?",
                "Que mange-t-il habituellement ?",
                "A-t-il des allergies ?",
                "Est-ce que je dois lui donner un bain ?",
                "À quelle heure se couche-t-il ?",
                "A-t-il des activités préférées ?",
                "Puis-je le sortir au parc ?",
                "A-t-il des jouets ou livres qu'il aime ?",
                "Que dois-je faire s'il pleure ?",
                "Y a-t-il un numéro à appeler en cas d'urgence ?",
                "Dois-je m'occuper de ses devoirs ?",
                "Est-ce que quelqu'un viendra le récupérer ou je dois rester jusqu'à ton retour ?",
            ),
        ),
    ]),
    part("tache2", 3, [
        sub(
            "Sujet 1",
            "Je suis votre ami(e). J'ai commencé un nouvel emploi et vous voulez savoir comment s'est déroulée ma première journée : l'ambiance, les collègues, les tâches, etc.",
            L(
                "Alors, comment s'est passée ta première journée de travail ?",
                "Tu t'es bien entendu(e) avec tes collègues ?",
                "L'ambiance dans ton entreprise est comment ?",
                "Tes tâches sont-elles faciles à comprendre ?",
                "Est-ce que ton supérieur t'a bien accueilli(e) ?",
                "Tu travailles seul(e) ou en équipe ?",
                "Quels sont tes horaires de travail ?",
                "Est-ce que ton trajet pour aller au travail est long ?",
                "Tu te sens à l'aise dans ce nouveau poste ?",
                "Tu penses que ce travail va te plaire sur le long terme ?",
            ),
        ),
        sub(
            "Sujet 2",
            "Je suis votre voisin(e). Je connais quelqu'un qui propose des cours de musique à domicile. Vous êtes intéressé(e) et vous me posez des questions sur cette personne : ses tarifs, sa disponibilité, son expérience, etc.",
            L(
                "Quels instruments enseigne cette personne ?",
                "Elle donne des cours à domicile ou en ligne aussi ?",
                "Quels sont ses tarifs ?",
                "Est-ce qu'elle enseigne aux enfants ou seulement aux adultes ?",
                "Depuis combien de temps donne-t-elle des cours ?",
                "Quelle est sa spécialité : guitare, piano, ou autre ?",
                "Est-ce qu'elle fournit le matériel pour les cours ?",
                "Quelle est sa disponibilité dans la semaine ?",
                "Les cours durent combien de temps ?",
                "Tu me la recommandes personnellement ?",
            ),
        ),
        sub(
            "Sujet 3",
            "Je suis votre voisin(e). Vous souhaitez organiser une sortie à la campagne avec vos amis. Vous me demandez des conseils pour l'organisation : les activités, le transport, le lieu, etc.",
            L(
                "Tu connais un bon endroit pour passer une journée à la campagne ?",
                "Quelles activités peut-on faire là-bas ?",
                "Est-ce qu'il y a des endroits pour pique-niquer ?",
                "On peut y aller en voiture ou en train ?",
                "Combien de temps faut-il pour y arriver ?",
                "Est-ce qu'il y a des restaurants ou il faut apporter à manger ?",
                "C'est mieux d'y aller le week-end ou en semaine ?",
                "Y a-t-il des sentiers pour faire une randonnée ?",
                "Faut-il réserver à l'avance pour y aller ?",
                "Tu veux venir avec nous ?",
            ),
        ),
        sub(
            "Sujet 4",
            "Je travaille dans un magasin d'alimentation. Vous êtes client(e) et vous voulez faire livrer vos courses chez vous. Vous me posez des questions sur les conditions offertes : délais, tarifs, mode de livraison, etc.",
            L(
                "Est-ce que vous proposez un service de livraison à domicile ?",
                "Quels sont les tarifs pour la livraison ?",
                "En combien de temps la commande est-elle livrée ?",
                "Est-ce que la livraison est possible tous les jours ?",
                "Faut-il un montant minimum d'achat pour se faire livrer ?",
                "Les produits frais sont-ils bien conservés pendant la livraison ?",
                "Puis-je payer directement en ligne ?",
                "Si je ne suis pas chez moi, que se passe-t-il ?",
                "Est-ce que vous livrez aussi dans mon quartier ?",
                "Peut-on choisir un créneau horaire précis pour la livraison ?",
            ),
        ),
        sub(
            "Sujet 5",
            "Je travaille dans une agence immobilière. Vous voulez louer votre appartement pour les vacances afin de gagner plus d'argent. Vous me demandez des conseils sur les prix, la durée de location, le type de locataires, etc.",
            L(
                "Pensez-vous que c'est une bonne idée de louer mon appartement pendant les vacances ?",
                "Combien pourrais-je demander par semaine ?",
                "Quels types de locataires recherchent ce genre d'appartement ?",
                "Est-ce que vous pouvez m'aider à trouver des clients ?",
                "Faut-il faire un contrat de location ?",
                "Dois-je déclarer ce revenu ?",
                "Est-ce que je dois fournir le linge et la vaisselle ?",
                "Comment assurer que l'appartement reste en bon état ?",
                "Y a-t-il beaucoup de demandes pendant l'été ?",
                "Vous conseillez plutôt une location courte ou longue durée ?",
            ),
        ),
    ]),
]
