# -*- coding: utf-8 -*-
"""Contenu T-che 2 - Expression orale Octobre 2025."""


def sub(title, prompt, correction, icon="bx bx-message-detail"):
    return {
        "title": title,
        "prompt": prompt.strip(),
        "correction": correction.strip(),
        "icon_class": icon,
    }


def part(task_key, part_num, subjects):
    return {
        "task_key": task_key,
        "part_number": part_num,
        "part_title": f"Partie {part_num}",
        "subjects": subjects,
    }


def q(lines):
    return "\n".join(f"{i + 1}. {line}" for i, line in enumerate(lines))


TACHE2 = [
    part("tache2", 1, [
        sub(
            "Sujet 1",
            "Je suis votre collègue. Vous venez d’intégrer l’entreprise et vous voulez mieux la connaître. Vous souhaitez obtenir des détails sur l’organisation, l’ambiance, la cantine, etc.",
            q([
                "Comment est organisée l’entreprise ?",
                "Quels sont les horaires de travail habituels ?",
                "Y a-t-il des réunions régulières ?",
                "Comment décririez-vous l’ambiance entre collègues ?",
                "L’entreprise est-elle plutôt formelle ou décontractée ?",
                "Existe-t-il des activités ou événements pour les employés ?",
                "La cantine est-elle bonne et abordable ?",
                "Y a-t-il des options pour les personnes ayant des régimes spécifiques ?",
                "Peut-on travailler à distance parfois ?",
                "L’entreprise propose-t-elle des formations ou des cours internes ?",
                "Comment se passent les pauses et le temps libre ?",
                "Les managers sont-ils accessibles et ouverts aux questions ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) ami(e) et je vous propose de venir à une célébration. Vous êtes nouvellement arrivé(e) au Québec. Vous me demandez des précisions sur l’organisation (horaire, cadeau, habits, etc.).",
            q([
                "À quelle heure commence la fête ?",
                "Combien de temps dure la célébration ?",
                "Où aura lieu la fête exactement ?",
                "Y a-t-il un thème pour la fête ?",
                "Que devrais-je apporter comme cadeau ?",
                "Faut-il apporter quelque chose à manger ou à boire ?",
                "Comment dois-je m’habiller pour la fête ?",
                "Y aura-t-il des activités ou des jeux pendant la fête ?",
                "Combien de personnes vont venir ?",
                "Est-ce que je peux venir avec quelqu’un d’autre ?",
                "Y aura-t-il de la musique ou des animations ?",
                "Faut-il confirmer ma présence avant la fête ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis à la réception du club de sport près de chez vous. Vous souhaitez pratiquer une activité mais vous n’avez pas encore choisi. Vous me demandez des informations sur les sports disponibles (horaires, tarifs, équipement, etc.).",
            q([
                "Quels sports proposez-vous ?",
                "Quels sont les horaires pour chaque activité ?",
                "Y a-t-il des cours pour débutants ?",
                "Les cours sont-ils mixtes ou séparés ?",
                "Quels sont les tarifs pour chaque sport ?",
                "Faut-il réserver à l’avance ?",
                "Quels équipements faut-il apporter soi-même ?",
                "Fournissez-vous le matériel nécessaire ?",
                "Y a-t-il des cours particuliers possibles ?",
                "Les activités sont-elles adaptées à tous les âges ?",
                "Comment s’inscrire pour une activité ?",
                "Y a-t-il des réductions pour les étudiants ou familles ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis à la réception d’un musée. Vous voulez venir le découvrir avec vos amis. Vous me demandez des informations pour préparer la visite (horaires, tarifs, visites guidées, etc.).",
            q([
                "Quelles sont les heures d’ouverture du musée ?",
                "Quel est le prix d’entrée pour un adulte ?",
                "Y a-t-il des tarifs réduits pour les étudiants ou enfants ?",
                "Combien de temps dure en moyenne la visite ?",
                "Peut-on réserver une visite guidée ?",
                "Les visites guidées sont-elles en français seulement ?",
                "Y a-t-il des expositions temporaires en ce moment ?",
                "Peut-on prendre des photos dans le musée ?",
                "Y a-t-il un café ou un restaurant à l’intérieur ?",
                "Existe-t-il un vestiaire pour laisser ses affaires ?",
                "Peut-on visiter le musée avec des animaux de compagnie ?",
                "Y a-t-il un parking à proximité ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Nous travaillons ensemble. Vous voulez organiser un week-end et je vous recommande une ville que je connais. Vous me demandez des informations (logement, restaurants, sites à découvrir, etc.).",
            q([
                "Quelle ville me recommandez-vous ?",
                "Quels sont les meilleurs hôtels ou hébergements ?",
                "Y a-t-il des auberges ou logements économiques ?",
                "Quels restaurants valent le détour ?",
                "Quels plats typiques peut-on goûter là-bas ?",
                "Quelles sont les attractions incontournables ?",
                "Y a-t-il des musées ou monuments intéressants ?",
                "Quels sont les bons endroits pour se promener ?",
                "La ville est-elle facile à visiter à pied ou faut-il une voiture ?",
                "Y a-t-il des événements ou festivals pendant le week-end ?",
                "Quels sont les quartiers les plus agréables pour séjourner ?",
                "Existe-t-il des activités adaptées pour les familles ou groupes d’amis ?",
            ]),
        ),
    ]),
    part("tache2", 2, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e) francophone. Vous devez préparer un article sur un film pour le journal de votre association culturelle. Vous cherchez des idées. Vous me posez des questions sur les films que j’ai aimés (endroit, genre, prix, etc.).",
            q([
                "Quel film as-tu vu récemment et que tu as vraiment aimé ?",
                "Où as-tu regardé ce film - Au cinéma ou à la maison ?",
                "Quel était le genre du film ?",
                "Combien as-tu payé pour aller le voir ?",
                "Est-ce que tu me le recommandes - Pourquoi ?",
                "Qui étaient les acteurs principaux ?",
                "Qu’est-ce qui t’a le plus plu dans ce film ?",
                "Le film était-il drôle, triste, ou plutôt émouvant ?",
                "Est-ce qu’il y avait des effets spéciaux impressionnants ?",
                "Quelle scène t’a le plus marqué ?",
                "Est-ce que tu connais le réalisateur du film ?",
                "Penses-tu que ce film serait intéressant pour notre journal culturel ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je travaille dans une agence de voyages. Vous voulez préparer des vacances. Vous venez me voir et vous me demandez des renseignements sur les lieux proposés (activités, visites, prix, etc.).",
            q([
                "Quels sont les endroits que vous proposez pour les vacances ?",
                "Quelles activités peut-on faire sur place ?",
                "Y a-t-il des visites guidées incluses dans les séjours ?",
                "Est-ce que vous proposez des formules tout compris ?",
                "Quels sont les prix moyens pour une semaine ?",
                "Avez-vous des réductions pour les familles ou les groupes ?",
                "Est-ce que le transport est inclus dans le prix ?",
                "Peut-on choisir l’hôtel soi-même ?",
                "Proposez-vous des voyages culturels ou plutôt de détente ?",
                "Y a-t-il des destinations adaptées aux enfants ?",
                "Quels sont les documents nécessaires pour voyager ?",
                "Est-ce qu’on peut réserver à l’avance et payer en plusieurs fois ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis votre voisin(e). Vous souhaitez organiser une rencontre conviviale entre habitants de l’immeuble. Vous me posez des questions pour avoir des idées (animations, invités, repas, etc.).",
            q([
                "Que pensez-vous d’organiser une rencontre entre voisins ?",
                "Préférez-vous que ce soit un déjeuner, un dîner ou juste un goûter ?",
                "Faut-il prévoir un repas partagé où chacun apporte quelque chose ?",
                "Quelles animations pourrions-nous proposer ?",
                "Pensez-vous qu’il serait bien d’inviter un musicien ou un artiste ?",
                "Préférez-vous une ambiance familiale ou plus festive ?",
                "Aimeriez-vous qu’on organise des jeux pour les enfants ?",
                "Selon vous, quel est le meilleur jour pour réunir les voisins ?",
                "Faut-il louer une salle ou utiliser la cour de l’immeuble ?",
                "Seriez-vous prêt(e) à aider pour l’organisation ?",
                "Avez-vous déjà participé à ce genre de rencontre ?",
                "Pensez-vous que ce type d’événement peut renforcer nos liens de voisinage ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis un(e) voisin(e). Vous vous êtes récemment installé(e) dans la ville et vous n’avez pas encore de relations. Vous me posez des questions pour savoir comment faire des connaissances.",
            q([
                "Savez-vous où je peux rencontrer des personnes dans le quartier ?",
                "Y a-t-il des associations culturelles ou sportives dans la ville ?",
                "Est-ce que les habitants se retrouvent parfois dans un café ou un parc ?",
                "Pensez-vous qu’il est utile de participer à des activités de bénévolat ?",
                "Y a-t-il un marché local où l’on peut discuter avec des gens ?",
                "Est-ce que la mairie organise des événements pour les nouveaux arrivants ?",
                "Me conseillez-vous de m’inscrire à un club de sport ?",
                "Comment font, en général, les nouveaux habitants pour s’intégrer ici ?",
                "Est-ce facile de parler avec ses voisins dans l’immeuble ?",
                "Y a-t-il des groupes sur les réseaux sociaux pour les habitants de la ville ?",
                "Est-ce qu’il existe une bibliothèque ou un centre culturel actif ?",
                "Selon vous, quelle est la meilleure façon de créer des liens dans cette ville ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Vous souhaitez connaître le rythme professionnel au Canada. Vous me demandez des informations sur les heures de travail et les vacances. Puis, vous faites une comparaison avec votre pays.",
            q([
                "Quelles sont les horaires de travail habituels au Canada ?",
                "Combien d’heures travaille-t-on par semaine en moyenne ?",
                "Y a-t-il des pauses pendant la journée de travail ?",
                "Combien de jours de congés les employés ont-ils par an ?",
                "Existe-t-il des jours fériés officiels en plus des vacances ?",
                "Est-ce que les entreprises respectent toujours ces horaires ?",
                "À quelle heure commence généralement la journée de travail ?",
                "Y a-t-il une différence entre le secteur public et le secteur privé ?",
                "Est-ce que les Canadiens travaillent souvent le week-end ?",
                "Le rythme de travail est-il plus intense qu’en Europe ?",
                "Est-ce que les congés sont mieux respectés qu’ailleurs ?",
                "Par rapport à mon pays, pensez-vous que le Canada offre un meilleur équilibre entre travail et vie privée ?",
            ]),
        ),
    ]),
    part("tache2", 3, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e). J’ai regardé un film hier au cinéma. Vous souhaitez en connaître davantage et vous me demandez des informations (titre, genre, histoire, acteurs, etc.).",
            q([
                "Quel est le titre du film que tu as vu ?",
                "De quel genre est ce film ?",
                "Peux-tu me résumer l’histoire ?",
                "Qui sont les acteurs principaux ?",
                "Le film était-il long ?",
                "L’histoire était-elle facile à comprendre ?",
                "As-tu aimé la fin du film ?",
                "Le film était-il drôle ou triste ?",
                "Le réalisateur est-il connu ?",
                "Le film était-il adapté pour tous les âges ?",
                "As-tu vu ce film en version originale ou doublée ?",
                "Le recommanderais-tu à tes amis ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) ami(e). Je viens de rentrer d’un séjour de deux semaines au Canada. Vous partez bientôt et vous me demandez des renseignements pratiques (prix, habitants, repas, climat, transports, etc.).",
            q([
                "Dans quelle ville as-tu passé ton séjour ?",
                "Comment étaient les habitants ?",
                "Quels étaient les prix là-bas pour les repas ou les transports ?",
                "As-tu trouvé le logement facilement ?",
                "Le climat était comment pendant ton séjour ?",
                "As-tu visité des endroits touristiques ?",
                "Quels plats as-tu goûtés ?",
                "Le transport était-il pratique pour se déplacer ?",
                "As-tu rencontré beaucoup de gens ?",
                "Combien coûtent les sorties ou activités typiques là-bas ?",
                "Quels conseils donnerais-tu pour un premier voyage au Canada ?",
                "Y a-t-il quelque chose que tu aurais fait différemment ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) ami(e). Je viens de planifier un voyage à la montagne. Vous souhaitez en savoir plus et vous me demandez des informations (hébergement, coût, activités, saison, etc.).",
            q([
                "Où se trouve exactement ce séjour à la montagne ?",
                "Quel type de logement as-tu réservé ?",
                "Combien coûte ce séjour environ ?",
                "Quelles activités peut-on faire là-bas ?",
                "Quelle est la meilleure saison pour y aller ?",
                "Y a-t-il des randonnées ou des excursions à faire ?",
                "Est-ce adapté pour les familles ou les enfants ?",
                "Y a-t-il des restaurants ou repas inclus dans le séjour ?",
                "Combien de temps dure le séjour idéal selon toi ?",
                "Les chambres sont-elles confortables ?",
                "Faut-il réserver longtemps à l’avance ?",
                "Recommanderais-tu ce séjour à tes amis ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis un(e) collègue. J’ai eu un accident mineur. Vous venez me rendre visite et vous me demandez des détails sur l’événement (moment, endroit, circonstances, etc.).",
            q([
                "Pouvez-vous me raconter ce qui s’est passé exactement ?",
                "À quel moment l’accident est-il arrivé ?",
                "Où cela s’est-il produit ?",
                "Étiez-vous seul(e) à ce moment-là ?",
                "Quelles circonstances ont provoqué l’accident ?",
                "Avez-vous été blessé(e) ?",
                "Avez-vous reçu des soins médicaux ?",
                "Y avait-il quelqu’un pour vous aider sur le moment ?",
                "L’accident a-t-il causé des dégâts matériels ?",
                "Comment vous sentez-vous maintenant ?",
                "Avez-vous signalé l’accident à votre responsable ou à la sécurité ?",
                "Que feriez-vous différemment si cela se reproduisait ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Vous venez d’arriver au Canada et vous souhaitez trouver un appartement. Vous me demandez des renseignements (type, procédures, quartier, etc.).",
            q([
                "Quel type de logement recherchez-vous exactement ?",
                "Dans quel quartier souhaitez-vous habiter ?",
                "Quels sont vos critères principaux pour choisir un appartement ?",
                "Quelles démarches avez-vous déjà effectuées ?",
                "Savez-vous quelles pièces sont obligatoires dans le contrat de location ?",
                "Avez-vous un budget précis pour le logement ?",
                "Quels transports sont disponibles dans le quartier ?",
                "Cherchez-vous un logement meublé ou vide ?",
                "Combien de temps souhaitez-vous rester dans cet appartement ?",
                "Avez-vous pensé aux charges et aux frais supplémentaires ?",
                "Connaissez-vous les règles pour la location au Canada ?",
                "Souhaitez-vous des conseils pour visiter les appartements ?",
            ]),
        ),
    ]),
    part("tache2", 4, [
        sub(
            "Sujet 1",
            "Je suis votre collègue. Je participe à un club de jeux de société. Vous souhaitez en savoir plus et me demandez des renseignements (lieu, prix, heures, ambiance, etc.).",
            q([
                "Où se situe exactement le club ?",
                "À quelles heures se déroulent les rencontres ?",
                "Y a-t-il une cotisation ou un tarif pour participer ?",
                "Faut-il s’inscrire à l’avance pour chaque séance ?",
                "Quel type de jeux proposez-vous ?",
                "Les jeux sont-ils adaptés aux débutants ?",
                "Combien de personnes participent généralement ?",
                "L’ambiance est-elle plutôt calme ou conviviale ?",
                "Est-ce que les repas ou boissons sont autorisés sur place ?",
                "Y a-t-il un animateur ou c’est libre ?",
                "Les membres peuvent-ils apporter leurs propres jeux ?",
                "Peut-on venir seulement pour essayer avant de s’inscrire ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis votre collègue. Je prépare une soirée pour célébrer ma retraite et vous êtes invité(e). Vous voulez en savoir plus (date, lieu, invités, programme, etc.).",
            q([
                "Quelle est la date exacte de la soirée ?",
                "Où aura lieu la fête ?",
                "À quelle heure devons-nous arriver ?",
                "Combien de personnes seront présentes ?",
                "Y aura-t-il un programme ou des animations prévues ?",
                "Faut-il apporter quelque chose pour la soirée ?",
                "Y aura-t-il un repas ou des boissons servies ?",
                "L’événement est-il formel ou décontracté ?",
                "Pouvons-nous venir avec un accompagnant ?",
                "Faut-il confirmer notre présence à l’avance ?",
                "La soirée sera-t-elle à l’intérieur ou en plein air ?",
                "Y aura-t-il de la musique ou un DJ ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) voisin(e). J’organise des activités de jardinage dans le quartier. Vous êtes intéressé(e) et vous me demandez des informations (coût, organisation, activités proposées, etc.).",
            q([
                "Quelles sont les activités proposées exactement ?",
                "Où se déroulent les ateliers de jardinage ?",
                "À quelle fréquence ont lieu ces activités ?",
                "Y a-t-il un coût pour participer ?",
                "Faut-il s’inscrire à l’avance ?",
                "Les enfants peuvent-ils participer ?",
                "Quels outils ou matériel faut-il apporter ?",
                "Combien de personnes participent habituellement ?",
                "L’activité est-elle encadrée par un spécialiste ?",
                "Les ateliers sont-ils adaptés aux débutants ?",
                "Y a-t-il un jardin spécifique pour chaque participant ?",
                "Les plantes ou récoltes sont-elles offertes aux participants ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis employé(e) à la bibliothèque municipale. Vous voulez emprunter des documents et vous me posez des questions sur la procédure (durée, quantité autorisée, conditions, etc.).",
            q([
                "Combien de documents peut-on emprunter à la fois ?",
                "Quelle est la durée maximale de prêt ?",
                "Faut-il avoir une carte de bibliothèque pour emprunter ?",
                "Y a-t-il des frais de retard ?",
                "Peut-on réserver des livres ou documents à l’avance ?",
                "Les revues et magazines peuvent-ils être empruntés ?",
                "Les documents numériques sont-ils disponibles pour prêt ?",
                "Y a-t-il des sections pour enfants ou adolescents ?",
                "La bibliothèque propose-t-elle des ateliers ou animations ?",
                "Peut-on prolonger un prêt si nécessaire ?",
                "Quels documents sont disponibles dans d’autres langues ?",
                "Faut-il un justificatif de domicile pour s’inscrire ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Je suis à la réception de la piscine municipale. Vous souhaitez prendre des leçons de natation et me demandez des renseignements (prix, horaires, accès, etc.).",
            q([
                "Quels sont les horaires des cours de natation ?",
                "Quel est le prix pour une séance ou un abonnement ?",
                "Les cours sont-ils adaptés à tous les âges ?",
                "Faut-il réserver sa place à l’avance ?",
                "Combien de personnes participent à chaque cours ?",
                "Y a-t-il différents niveaux pour débutants et avancés ?",
                "Quels équipements faut-il apporter (maillot, bonnet, lunettes) ?",
                "Les cours sont-ils encadrés par un maître-nageur qualifié ?",
                "Peut-on prendre des cours particuliers ?",
                "Y a-t-il des réductions pour les familles ou les étudiants ?",
                "Quelle est la durée de chaque leçon ?",
                "L’accès à la piscine est-il autorisé avant ou après le cours pour nager librement ?",
            ]),
        ),
    ]),
    part("tache2", 5, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e) et je m’en vais en vacances pour un moment. Je vous confie la surveillance de mon appartement durant ce temps. Vous me demandez des précisions (dates, choses à faire, instructions, etc.).",
            q([
                "Tu pars à quelle date exactement ?",
                "Et tu reviens quand ?",
                "Quelles tâches aimerais-tu que je fasse pendant ton absence ?",
                "Dois-je arroser les plantes et, si oui, combien de fois par semaine ?",
                "Est-ce que tu veux que je récupère ton courrier ou tes colis ?",
                "Y a-t-il des animaux à nourrir ou à surveiller ?",
                "Dois-je vérifier les fenêtres et les portes chaque jour ?",
                "Quelles sont les instructions en cas d’urgence, comme une fuite ou une panne ?",
                "Dois-je utiliser certains appareils ou lumières pour donner l’impression que tu es là ?",
                "Est-ce que tu veux que je nettoie un peu ou juste surveille ?",
                "Y a-t-il des voisins ou amis que je devrais contacter en cas de problème ?",
                "Où puis-je te joindre facilement si j’ai besoin de te parler ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) ami(e) et je me suis installé(e) au Québec il y a deux ans. Vous souhaitez vivre à l’étranger et vous me demandez des renseignements sur mon expérience (adaptation, obstacles, changements de mode de vie, etc.).",
            q([
                "Comment s’est passée ton arrivée au Québec ?",
                "As-tu eu des difficultés pour trouver un logement ?",
                "Est-ce que la langue a été un obstacle pour toi ?",
                "Comment as-tu trouvé l’adaptation à la culture locale ?",
                "Quelles différences as-tu remarquées avec ton pays d’origine ?",
                "Est-ce que la nourriture ou le climat t’ont posé des problèmes au début ?",
                "Comment as-tu fait pour te faire des amis ?",
                "Est-ce que le travail ou les études étaient faciles à trouver ?",
                "Quels conseils donnerais-tu à quelqu’un qui veut s’installer là-bas ?",
                "Est-ce que tu as changé certaines habitudes de vie depuis ton arrivée ?",
                "Qu’est-ce que tu apprécies le plus au Québec ?",
                "Y a-t-il quelque chose que tu regrettes ou que tu aurais aimé mieux préparer avant de partir ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) voisin(e) et j’enseigne le piano dans une école de musique du quartier. Vous souhaitez prendre des cours et vous me demandez des informations sur l’établissement (types de cours, prix, horaires, etc.).",
            q([
                "Pourriez-vous me dire quels types de cours de piano vous proposez ?",
                "Est-ce que les cours sont individuels ou en groupe ?",
                "Quels sont les horaires disponibles pour les cours ?",
                "Combien de temps dure chaque séance ?",
                "Quel est le tarif pour un cours individuel par semaine ?",
                "Est-ce que vous proposez des forfaits pour plusieurs séances ?",
                "Les cours sont-ils adaptés aux débutants ou seulement aux élèves avancés ?",
                "Quel âge minimum faut-il pour commencer les cours ?",
                "Est-ce que vous fournissez le piano ou faut-il en avoir un à la maison ?",
                "Y a-t-il des concerts ou des examens pour les élèves ?",
                "Comment se déroule l’inscription aux cours ?",
                "Acceptez-vous des élèves avec des horaires variables ou flexibles ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis un(e) voisin(e) et j’anime des activités sportives dans une association du quartier. Vous voulez rejoindre mes séances et vous me demandez des informations sur les entraînements (conditions, discipline, horaires, etc.).",
            q([
                "Pourriez-vous m’expliquer quelles activités sportives vous proposez ?",
                "Est-ce que les séances sont ouvertes à tous les niveaux ?",
                "Quels sont les horaires et les jours des entraînements ?",
                "Y a-t-il un âge minimum ou maximum pour participer ?",
                "Est-ce qu’il faut s’inscrire à l’avance ou peut-on venir directement ?",
                "Quel est le tarif pour participer aux séances ?",
                "Est-ce que vous fournissez le matériel ou faut-il venir avec son propre équipement ?",
                "Combien de personnes participent généralement à une séance ?",
                "Y a-t-il un encadrement particulier pour les débutants ?",
                "Est-ce que les activités se déroulent à l’intérieur ou en extérieur ?",
                "Organisez-vous des événements ou compétitions pour les participants ?",
                "Peut-on tester une séance avant de s’inscrire officiellement ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Vous avez l’intention de découvrir une région du Québec. Vous venez à l’office du tourisme pour vous informer sur les options d’hébergement (catégories, localisation, tarifs, etc.). Je suis la personne qui vous renseigne.",
            q([
                "Pourriez-vous me dire quelles catégories d’hébergement sont disponibles dans la région ?",
                "Quels sont les tarifs moyens pour chaque type d’hébergement ?",
                "Où sont situés les différents hébergements par rapport aux attractions principales ?",
                "Est-ce que vous proposez des hôtels, des gîtes ou des auberges ?",
                "Est-il possible de réserver directement depuis votre office du tourisme ?",
                "Y a-t-il des options adaptées aux familles avec enfants ?",
                "Quels hébergements offrent des services supplémentaires, comme le petit-déjeuner ou le wifi ?",
                "Est-ce que certaines périodes de l’année sont plus chères que d’autres ?",
                "Combien de temps à l’avance faut-il réserver pour être sûr d’avoir une place ?",
                "Est-il possible de choisir des hébergements proches des transports en commun ?",
                "Y a-t-il des hébergements recommandés pour les personnes à mobilité réduite ?",
                "Pouvez-vous me fournir des brochures ou un guide avec toutes les options disponibles ?",
            ]),
        ),
    ]),
    part("tache2", 6, [
        sub(
            "Sujet 1",
            "Je suis votre collègue de travail. J’aimerais trouver un partenaire pour faire du sport. Vous êtes curieux(se) et vous me demandez des précisions sur ce sport (genre d’activité, heures, niveau, etc.).",
            q([
                "Quel type de sport faites-vous exactement ?",
                "Depuis combien de temps pratiquez-vous ce sport ?",
                "Est-ce un sport d’équipe ou individuel ?",
                "Vous pratiquez ce sport en salle ou en plein air ?",
                "À quelle fréquence faites-vous du sport chaque semaine ?",
                "À quelles heures vous entraînez-vous d’habitude ?",
                "Est-ce que le niveau est plutôt débutant ou avancé ?",
                "Faut-il un équipement particulier pour participer ?",
                "Où se déroulent généralement les séances ?",
                "Y a-t-il des frais d’inscription ou c’est gratuit ?",
                "Combien de personnes participent en général ?",
                "Vous pensez que ce sport est accessible à tout le monde ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) voisin(e) et nos enfants sont copains. Je vous suggère que votre enfant nous accompagne pendant nos vacances. Vous me demandez des renseignements avant de dire oui (dates, destination, activités, etc.).",
            q([
                "Où partez-vous exactement en vacances ?",
                "Quelles sont les dates prévues pour le départ et le retour ?",
                "Comment comptez-vous vous déplacer ?",
                "Où allez-vous loger pendant les vacances ?",
                "Combien de personnes partiront avec vous ?",
                "Y aura-t-il d’autres enfants du même âge ?",
                "Quelles activités prévoyez-vous pour les enfants ?",
                "Est-ce qu’il y a une surveillance permanente ?",
                "Quelle est la durée du séjour ?",
                "Y a-t-il des frais à prévoir pour les parents ?",
                "Mon enfant aura-t-il besoin d’apporter quelque chose de spécial ?",
                "En cas de problème, comment puis-je vous joindre pendant le voyage ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) voisin(e) et je fais du bénévolat dans une association qui protège l’environnement. Vous êtes intéressé(e) par y participer et vous me demandez des précisions (activités, heures, membres, etc.).",
            q([
                "Depuis quand existe votre association ?",
                "Quel est exactement le but de votre association ?",
                "Quelles sont les principales activités que vous organisez ?",
                "À quelle fréquence les bénévoles se réunissent-ils ?",
                "Les activités se déroulent plutôt en semaine ou le week-end ?",
                "Faut-il avoir des compétences particulières pour participer ?",
                "Combien de temps faut-il consacrer chaque semaine ?",
                "Combien de membres font partie de l’association ?",
                "Où se déroulent généralement les actions ?",
                "Y a-t-il une cotisation à payer pour être membre ?",
                "Est-ce qu’il y a des activités pour les familles ou les enfants ?",
                "Comment puis-je m’inscrire ou vous rejoindre ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis employé(e) dans une agence de voyages spécialisée dans les excursions d’une journée. Vous souhaitez en savoir plus et vous me demandez des précisions (prix, programme, destinations, etc.).",
            q([
                "Quelles sont les principales destinations que vous proposez ?",
                "Les excursions durent combien d’heures environ ?",
                "Le transport est-il inclus dans le prix ?",
                "Combien coûte une excursion en moyenne ?",
                "À quelle heure part-on généralement le matin ?",
                "Quel type d’activités sont prévues pendant la journée ?",
                "Le déjeuner est-il compris dans le tarif ?",
                "Faut-il réserver à l’avance ?",
                "Y a-t-il des réductions pour les familles ou les groupes ?",
                "Combien de personnes participent habituellement ?",
                "En cas de mauvais temps, l’excursion est-elle annulée ?",
                "Est-ce qu’il y a un guide qui accompagne le groupe ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Je suis employé(e) à la réception d’un musée. Vous voulez organiser une visite en famille et vous me demandez des précisions (horaires, expositions, tarifs, etc.).",
            q([
                "Quels sont les horaires d’ouverture du musée ?",
                "Quels jours êtes-vous ouverts ?",
                "Quelles expositions sont présentées en ce moment ?",
                "Y a-t-il une exposition spéciale pour les enfants ?",
                "Combien coûte le billet d’entrée ?",
                "Avez-vous des tarifs réduits pour les familles ?",
                "Faut-il réserver à l’avance ?",
                "Y a-t-il des visites guidées disponibles ?",
                "Combien de temps dure en général la visite ?",
                "Peut-on prendre des photos à l’intérieur ?",
                "Y a-t-il une cafétéria ou un espace de repos dans le musée ?",
                "Le musée est-il accessible pour les poussettes ou les personnes à mobilité réduite ?",
            ]),
        ),
    ]),
    part("tache2", 7, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e). Vous êtes récemment arrivé(e) dans ma ville. Vous cherchez à organiser une sortie économique et vous me demandez des renseignements (endroits, activités, transports, etc.).",
            q([
                "Quels endroits intéressants puis-je visiter sans trop dépenser ?",
                "Connais‑tu des parcs ou jardins gratuits à voir ?",
                "Y a-t-il des musées ou expositions à tarif réduit ?",
                "Quels cafés ou restaurants proposent des menus économiques ?",
                "Peux‑tu me recommander des marchés ou foires sympas ?",
                "Y a-t-il des activités gratuites ou peu coûteuses à faire en ville ?",
                "Quels quartiers valent la peine d’être visités à pied ?",
                "Quels sont les moyens de transport les moins chers pour se déplacer ?",
                "Y a-t-il des événements ou festivals gratuits en ce moment ?",
                "Connais‑tu des lieux où l’on peut faire du sport ou se détendre gratuitement ?",
                "Quels endroits offrent de belles vues ou des points photo gratuits ?",
                "Peux‑tu me donner des astuces pour profiter de la ville sans trop dépenser ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) voisin(e). Je dispose d’une maison de vacances en bord de mer que je propose à la location. Vous souhaitez en savoir plus et vous me demandez des précisions (aménagements, lieu, tarif, etc.).",
            q([
                "Pourriez-vous me décrire la maison de vacances ?",
                "Combien de chambres et de lits y a-t-il ?",
                "Y a-t-il une cuisine équipée et des appareils électroménagers ?",
                "Quels équipements extérieurs sont disponibles (terrasse, jardin, piscine, etc.) ?",
                "La maison est-elle proche de la plage ?",
                "Y a-t-il des commerces ou restaurants à proximité ?",
                "Quelle est la capacité maximale d’accueil ?",
                "Quel est le tarif par nuit ou par semaine ?",
                "Faut-il prévoir un dépôt de garantie ?",
                "Y a-t-il des frais supplémentaires (ménage, électricité, etc.) ?",
                "Est-elle disponible à certaines périodes de l’année ?",
                "Pouvez-vous me dire comment réserver la maison ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis employé(e) dans une boutique de mobilier. Vous désirez recevoir un meuble et vous me demandez des informations sur la livraison (coût, délai, moyen utilisé, etc.).",
            q([
                "Pourriez-vous me préciser le coût de la livraison ?",
                "Combien de temps faut-il pour recevoir le meuble ?",
                "Quels moyens de transport utilisez-vous pour la livraison ?",
                "Livrez-vous à domicile ou en point relais seulement ?",
                "Y a-t-il un service de montage inclus ou en option ?",
                "Quels sont les horaires de livraison possibles ?",
                "Proposez-vous une assurance en cas de dommage pendant le transport ?",
                "Faut-il payer à la commande ou à la livraison ?",
                "Puis-je suivre la livraison en temps réel ?",
                "Y a-t-il des restrictions selon la taille ou le poids du meuble ?",
                "Que se passe-t-il si je ne suis pas chez moi lors de la livraison ?",
                "Puis-je changer la date de livraison après la commande ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Dans la salle d’attente, nous attendons le train qui a pris du retard et nous discutons un peu. Je vous parle de mon intérêt pour la montagne, et vous me demandez des détails (régions, randonnées, équipement, etc.).",
            q([
                "Quelles régions de montagne préférez-vous visiter ?",
                "Quelles randonnées recommandez-vous dans ces régions ?",
                "Y a-t-il des sentiers adaptés aux débutants ou aux enfants ?",
                "Quels équipements sont indispensables pour vos randonnées ?",
                "Avez-vous déjà fait des randonnées plus difficiles ou techniques ?",
                "Préférez-vous partir en été ou en hiver pour la montagne ?",
                "Y a-t-il des refuges ou hébergements sur les sentiers ?",
                "Quels paysages ou points de vue sont à ne pas manquer ?",
                "Faut-il prévoir un guide pour certaines randonnées ?",
                "Y a-t-il des activités autres que la randonnée à faire en montagne ?",
                "Quels conseils donneriez-vous à quelqu’un qui débute en montagne ?",
                "Y a-t-il des dangers particuliers à connaître avant de partir ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Nous participons à une soirée et nous venons de faire connaissance. Je vous mentionne que je reviens tout juste d’un séjour, et vous me demandez des informations (période, endroits visités, avis, etc.).",
            q([
                "Quand avez-vous effectué ce séjour ?",
                "Dans quel pays ou quelle ville êtes-vous allé(e) ?",
                "Quels endroits avez-vous visités pendant le séjour ?",
                "Avez-vous essayé des activités particulières sur place ?",
                "Quel moyen de transport avez-vous utilisé pour voyager ?",
                "Avez-vous logé dans un hôtel, une location ou chez des amis ?",
                "Quels plats ou spécialités locales avez-vous goûtés ?",
                "Qu’est-ce que vous avez le plus apprécié pendant le séjour ?",
                "Y a-t-il quelque chose que vous n’avez pas aimé ou que vous éviteriez ?",
                "Recommanderiez-vous ce séjour à d’autres personnes ?",
                "Combien de temps a duré votre séjour ?",
                "Avez-vous pris beaucoup de photos ou de souvenirs à rapporter ?",
            ]),
        ),
    ]),
    part("tache2", 8, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e) francophone. Vous avez pour mission de préparer un article à propos d’un spectacle pour le bulletin de votre association culturelle francophone. Vous voulez trouver des idées et vous m’interrogez sur les spectacles que j’ai aimés (coût, type, lieu, etc.).",
            q([
                "Dis-moi, quel a été le dernier spectacle que tu as vu ?",
                "Tu te souviens où il avait lieu ?",
                "Quel type de spectacle c’était (théâtre, concert, danse, etc.) ?",
                "Est-ce que tu l’as aimé - Pourquoi ?",
                "Combien coûtait le billet d’entrée ?",
                "Est-ce que tu trouves que le prix en valait la peine ?",
                "Le lieu du spectacle était-il grand ou plutôt intime ?",
                "L’ambiance était comment, selon toi ?",
                "Tu y es allé seul ou avec des amis ?",
                "Est-ce que tu connais d’autres spectacles intéressants à venir ?",
                "Quel genre de spectacle me conseillerais-tu d’aller voir ?",
                "Si tu devais écrire un article sur ce spectacle, qu’est-ce que tu mettrais en avant ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) collègue et je connais bien la ville de Montréal. Vous allez y séjourner une semaine pour des raisons professionnelles. Vous me demandez des précisions sur les transports publics (heures, prix, organisation, etc.).",
            q([
                "Pourriez-vous me dire quels sont les principaux moyens de transport à Montréal ?",
                "Est-ce que les bus et le métro fonctionnent tard le soir ?",
                "Savez-vous combien coûte un ticket de transport ?",
                "Y a-t-il des abonnements pour une semaine ?",
                "Où peut-on acheter les billets ou les cartes de transport ?",
                "Est-ce que le métro dessert bien le centre-ville ?",
                "Les transports sont-ils ponctuels en général ?",
                "Faut-il valider le ticket à chaque trajet ?",
                "Y a-t-il une application utile pour planifier les déplacements ?",
                "Est-ce que les bus sont fréquents le week-end ?",
                "Le métro est-il facile à utiliser pour quelqu’un qui ne connaît pas la ville ?",
                "Auriez-vous des conseils pour se déplacer rapidement sans perdre de temps ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis votre enseignant de français. Notre école de langues met en place un jeu pour les étudiants. Vous me demandez des informations pour en savoir davantage sur son organisation (règles, prix, modalités, etc.).",
            q([
                "Pourriez-vous m’expliquer en quoi consiste exactement le jeu ?",
                "Quelles sont les règles principales à respecter ?",
                "Est-ce que la participation est obligatoire ou facultative ?",
                "Combien de temps dure le jeu ?",
                "Faut-il former des équipes ou jouer individuellement ?",
                "Y a-t-il des prix à gagner ?",
                "Quels sont les critères pour être sélectionné ou gagner ?",
                "Où se déroulera l’activité ?",
                "Est-ce que le jeu aura lieu pendant les cours ou en dehors ?",
                "Faut-il s’inscrire quelque part pour participer ?",
                "Ce jeu a-t-il un objectif pédagogique particulier ?",
                "Pourriez-vous me donner un exemple de défi ou d’épreuve du jeu ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis votre supérieur. Notre entreprise vous offre une opportunité de travail à l’étranger. Avant de prendre votre décision, vous désirez en savoir davantage. Vous m’interrogez sur les détails du poste (missions, salaire, bénéfices, etc.).",
            q([
                "Pourriez-vous me préciser le pays où se trouve le poste ?",
                "Quelles seront exactement mes missions sur place ?",
                "Le poste est-il temporaire ou permanent ?",
                "Quel serait le salaire proposé ?",
                "Y a-t-il des avantages liés à ce poste (logement, transport, assurance, etc.) ?",
                "Est-ce que je travaillerai avec une nouvelle équipe sur place ?",
                "Quelle est la durée prévue pour cette mission ?",
                "L’entreprise prend-elle en charge les frais de voyage ?",
                "Y aura-t-il une formation avant le départ ?",
                "Est-il possible de revenir au poste actuel après la mission ?",
                "Quelles compétences particulières sont attendues pour ce poste ?",
                "Quand devrais-je donner ma réponse définitive ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Vous souhaitez faire une sortie ce soir, mais vous ne savez pas encore quoi faire. Nous en discutons entre amis et vous me posez des questions pour choisir une activité (endroit, transport, prix, etc.).",
            q([
                "Avez-vous une idée d’endroit sympa où sortir ce soir ?",
                "Préférez-vous un endroit calme ou plutôt animé ?",
                "Est-ce que vous connaissez un bon restaurant ou café à proximité ?",
                "Souhaitez-vous qu’on aille au cinéma ?",
                "Avez-vous envie d’une activité en plein air ?",
                "Quel budget souhaitez-vous mettre pour la soirée ?",
                "Comment pourrions-nous nous y rendre, en bus ou en voiture ?",
                "L’endroit est-il facile d’accès ?",
                "À quelle heure voulez-vous sortir ?",
                "Faut-il réserver à l’avance ?",
                "Y a-t-il des événements particuliers ce soir en ville ?",
                "Préférez-vous qu’on sorte en petit groupe ou avec plusieurs amis ?",
            ]),
        ),
    ]),
    part("tache2", 9, [
        sub(
            "Sujet 1",
            "Je suis un(e) ami(e). Mon anniversaire arrive bientôt ; vous souhaitez organiser une fête et vous m’interrogez sur les détails (endroit, heures, invités, ambiance, etc.).",
            q([
                "C’est quand exactement ton anniversaire ?",
                "Où aimerais‑tu que la fête ait lieu ?",
                "À quelle heure voudrais‑tu commencer et finir ?",
                "Combien d’invités veux‑tu inviter ?",
                "Préfères‑tu une fête à la maison ou dans un lieu spécial ?",
                "Quel type d’ambiance veux‑tu (calme, festive, musicale) ?",
                "Souhaites‑tu un thème pour la fête ?",
                "Veux‑tu qu’on prépare des jeux ou des activités pendant la soirée ?",
                "Quel style de musique aimerais‑tu avoir ?",
                "Est-ce que tu veux un gâteau particulier ou des snacks spécifiques ?",
                "Faut‑il prévoir un budget précis pour la fête ?",
                "As‑tu besoin d’aide pour envoyer les invitations ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis un(e) ami(e). Je désire continuer mes études au Canada. Vous me demandez des informations pour en savoir plus sur mon projet (ville, spécialité, buts, etc.).",
            q([
                "Dans quelle ville du Canada veux‑tu étudier ?",
                "Quelle spécialité ou filière souhaites‑tu suivre ?",
                "Pourquoi as‑tu choisi cette ville et cette spécialité ?",
                "Combien de temps comptes‑tu rester là‑bas ?",
                "As‑tu déjà trouvé une école ou une université ?",
                "Quel est ton objectif principal avec ces études ?",
                "Préfères‑tu étudier en anglais ou en français ?",
                "As‑tu besoin d’aide pour les démarches administratives ou le visa ?",
                "Connais‑tu déjà des gens qui vivent ou étudient au Canada ?",
                "As‑tu réfléchi à ton logement sur place ?",
                "Quel budget comptes‑tu prévoir pour ton séjour ?",
                "Souhaites‑tu travailler en parallèle de tes études ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) ami(e). J’ai des objets lourds à transporter et aucun véhicule pour le faire. Vous me demandez des précisions pour m’aider à organiser cela (nature d'objets, distance, date, etc.).",
            q([
                "Quels objets dois‑tu transporter exactement ?",
                "Sont‑ils fragiles ou dangereux ?",
                "Combien pèsent approximativement ces objets ?",
                "Quelle distance faut‑il parcourir pour les transporter ?",
                "As‑tu une date précise pour ce transport ?",
                "Veux‑tu louer un véhicule ou trouver quelqu’un pour t’aider ?",
                "As‑tu besoin de plusieurs personnes pour le déménagement ?",
                "Est‑ce que les objets sont déjà emballés ou faut‑il les préparer ?",
                "Le trajet est‑il en ville ou sur une route plus longue ?",
                "Faut‑il faire plusieurs allers-retours ou tout transporter en une fois ?",
                "As‑tu pensé à demander de l’aide à des amis ou à des professionnels ?",
                "Veux‑tu que je t’aide à organiser le transport du début à la fin ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis un(e) voisin(e). Je peux vous recommander quelqu’un qui s’occupe des enfants à domicile. Vous souhaitez en savoir plus et me demandez des renseignements sur cette personne (prix, disponibilité, compétences, etc.).",
            q([
                "Pourriez-vous me donner le nom de la personne ?",
                "Depuis combien de temps travaille-t-elle dans ce domaine ?",
                "Quelles sont ses compétences principales avec les enfants ?",
                "Accepte-t-elle de s’occuper d’enfants de tous âges ?",
                "Quels sont ses horaires de disponibilité ?",
                "Est-elle disponible en soirée ou le week-end ?",
                "Quel est le tarif pour ses services ?",
                "Faut-il payer à l’heure ou à la journée ?",
                "Dispose-t-elle de références ou de recommandations d’autres familles ?",
                "Est-elle formée en premiers secours ou en sécurité des enfants ?",
                "Fait-elle des activités éducatives ou récréatives avec les enfants ?",
                "Pouvez-vous me dire si elle est flexible en cas de besoin exceptionnel ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Je suis employé(e) à l’office de tourisme canadien. Vous voulez passer un week-end relaxant et vous me demandez des recommandations (sorties, endroits à découvrir, déplacements, etc.).",
            q([
                "Pourriez-vous me conseiller des endroits incontournables à visiter ?",
                "Quelles activités de détente me recommanderiez-vous pour un week-end ?",
                "Quels sont les meilleurs restaurants ou cafés à découvrir ?",
                "Y a-t-il des événements ou festivals ce week-end ?",
                "Quels sont les moyens de transport les plus pratiques pour se déplacer ?",
                "Pouvez-vous me recommander des endroits calmes pour se reposer ?",
                "Y a-t-il des sites naturels ou parcs à ne pas manquer ?",
                "Quels quartiers valent la peine d’être visités ?",
                "Est-il préférable de réserver les activités à l’avance ?",
                "Existe-t-il des visites guidées intéressantes pour découvrir la ville rapidement ?",
                "Quelles précautions devrais-je prendre pour profiter pleinement de ce week-end ?",
                "Pouvez-vous me suggérer un itinéraire idéal pour optimiser mon temps ?",
            ]),
        ),
    ]),
    part("tache2", 10, [
        sub(
            "Sujet 1",
            "Je suis agent d’accueil dans un bureau d’information sur les associations de la ville. Vous voulez être bénévole dans une association de votre quartier. Vous me posez des questions (types, activités, publics, planning, etc.).",
            q([
                "Pourriez-vous me dire quelles associations existent dans le quartier ?",
                "Y a-t-il des associations qui recherchent actuellement des bénévoles ?",
                "Quels types d’activités proposent ces associations ?",
                "Est-ce qu’il y a des associations qui travaillent avec les enfants ?",
                "Et d’autres plutôt orientées vers les personnes âgées ?",
                "Faut-il avoir une expérience particulière pour être bénévole ?",
                "Combien d’heures faut-il consacrer par semaine en général ?",
                "Les bénévoles reçoivent-ils une formation avant de commencer ?",
                "Est-ce possible de choisir ses horaires ?",
                "Les activités se passent plutôt en semaine ou le week-end ?",
                "Est-ce que je peux m’inscrire directement ici ?",
                "Pourriez-vous me donner des contacts ou des brochures, s’il vous plaît ?",
            ]),
        ),
        sub(
            "Sujet 2",
            "Je suis professeur de français. Vous venez d’arriver au Canada, vous voulez prendre des cours particuliers. Vous m’interrogez sur mon parcours professionnel (expérience, méthodes, tarifs, etc.).",
            q([
                "Pourriez-vous me parler un peu de votre parcours professionnel ?",
                "Depuis combien de temps enseignez-vous le français ?",
                "Avez-vous déjà travaillé avec des apprenants étrangers ?",
                "Quelles méthodes utilisez-vous pendant vos cours ?",
                "Proposez-vous des cours individuels ou en petits groupes ?",
                "Est-ce que vos cours se font en ligne ou en présentiel ?",
                "Combien de temps dure une séance en général ?",
                "Quels sont vos tarifs pour une heure de cours ?",
                "Faut-il payer à l’avance ou après chaque séance ?",
                "Fournissez-vous des supports de cours ou des exercices à la maison ?",
                "Avez-vous des disponibilités en soirée ou le week-end ?",
                "Est-ce possible de faire un premier cours d’essai ?",
            ]),
        ),
        sub(
            "Sujet 3",
            "Je suis un(e) ami(e) canadien(ne). Je viens de passer des vacances formidables à la montagne. Vous voulez faire la même chose. Vous me posez des questions sur mon séjour (lieu, activités, hébergement, etc.).",
            q([
                "Où est-ce que tu es parti en vacances à la montagne ?",
                "C’était loin de chez toi ?",
                "Tu y es resté combien de temps ?",
                "Le paysage était comment ?",
                "Quelles activités as-tu faites là-bas ?",
                "Tu as fait du ski ou de la randonnée ?",
                "Le temps était beau pendant ton séjour ?",
                "Tu étais logé dans un hôtel ou un chalet ?",
                "C’était cher comme séjour ?",
                "Tu as goûté des plats typiques de la région ?",
                "Est-ce que tu conseillerais ce lieu pour des vacances ?",
                "Tu pourrais me donner le nom de l’endroit ou du logement ?",
            ]),
        ),
        sub(
            "Sujet 4",
            "Je suis votre ami(e). Je prends des cours de théâtre toutes les semaines. Vous voulez vous inscrire à ces cours. Vous me posez des questions pour avoir des informations (tarifs, horaires, organisation, etc.).",
            q([
                "Depuis combien de temps tu prends des cours de théâtre ?",
                "Où est-ce que tu les suis ?",
                "Les cours sont à quel moment de la semaine ?",
                "Combien de temps dure chaque séance ?",
                "Combien ça coûte par mois ?",
                "Il faut s’inscrire pour l’année ou au mois ?",
                "Le groupe est grand ou plutôt petit ?",
                "Le professeur est sympa ?",
                "On fait surtout des exercices ou des mises en scène ?",
                "Faut-il avoir déjà de l’expérience en théâtre ?",
                "Vous préparez parfois des spectacles ?",
                "Tu penses que je pourrais m’y plaire aussi ?",
            ]),
        ),
        sub(
            "Sujet 5",
            "Vous venez d’arriver au Québec. Je suis votre voisin(e). Je vous ai invité(e) à un apéritif de bienvenue. Pendant l’apéritif, vous me posez des questions pour avoir des informations sur la vie du quartier (voisins, services, activités, etc.).",
            q([
                "Pour commencer, comment trouvez-vous le quartier ?",
                "Est-ce un endroit plutôt calme ou animé ?",
                "Les voisins sont-ils sympathiques ?",
                "Est-ce que les gens se connaissent entre eux ?",
                "Y a-t-il des commerces ou des services à proximité ?",
                "Où se trouve le supermarché le plus proche ?",
                "Est-ce qu’il y a une école ou une garderie dans le quartier ?",
                "Les transports en commun sont-ils faciles d’accès ?",
                "Connaissez-vous un bon médecin ou une pharmacie dans le coin ?",
                "Y a-t-il des parcs ou des espaces verts pour se promener ?",
                "Le quartier organise-t-il parfois des activités ou des fêtes ?",
                "Auriez-vous un conseil pour bien s’intégrer ici ?",
            ]),
        ),
    ]),
]
