<?php
declare(strict_types=1);

/**
 * Données Expression écrite — Août 2025 (16 combinaisons).
 * @return list<array{combo:int,tasks:list<array{task:int,prompt:string,correction:string,documents?:list<array{title?:string,content:string}>}>}>
 */
return [
    [
        'combo' => 1,
        'tasks' => [
            [
                'task' => 1,
                'prompt' => 'Vous voulez aller à un festival de films dans votre ville. Rédigez un message à un ami pour lui proposer de vous accompagner. Indiquez clairement les détails de l\'événement (films, horaires, dates et prix).',
                'correction' => "Salut Martin,\n\nJe voulais t'inviter à un festival de cinéma qui aura lieu dans notre ville du 12 au 15 septembre. Plusieurs films seront projetés, notamment des films internationaux et aussi des courts-métrages locaux. Les séances commencent à 15h et finissent vers 21h. Le billet coûte 40 dollars par jour, et il y a une réduction pour les étudiants. J'aimerais y aller samedi pour découvrir deux films intéressants. Ce serait vraiment agréable si tu pouvais venir avec moi. Dis-moi si tu es disponible !\n\nÀ bientôt,\nelite tcf canada",
            ],
            [
                'task' => 2,
                'prompt' => 'Vous êtes allé à un festival de cinéma et vous avez regardé un film qui vous a laissé une forte impression. Rédigez un message à vos amis pour partager votre expérience et leur donner votre avis sur ce film.',
                'correction' => "Trois raisons d'aller au festival de cinéma de ma ville\n\nLa semaine dernière, j'ai participé au festival de cinéma organisé dans ma ville, un événement très attendu qui réunit chaque année des passionnés du grand écran. Pendant plusieurs jours, on pouvait découvrir des films étrangers, assister à des rencontres avec des réalisateurs et profiter d'une ambiance conviviale.\n\nParmi les films proposés, celui qui m'a le plus marqué est « Les Voix du silence », un drame émouvant sur la mémoire et la réconciliation. Le scénario était bien construit, les acteurs impressionnants et certaines scènes m'ont profondément touché. Ce film m'a fait réfléchir sur l'importance du pardon dans nos vies.\n\nJe recommande vivement à mes amis d'assister à ce festival. C'est une excellente occasion de découvrir des films différents de ceux qu'on voit d'habitude et de vivre une expérience culturelle enrichissante.",
            ],
            [
                'task' => 3,
                'prompt' => 'Les maisons de retraite, pour ou contre ?',
                'documents' => [
                    ['title' => 'Document 1', 'content' => 'Les maisons de retraite représentent une solution adaptée pour les personnes âgées. Elles y bénéficient de soins appropriés et d\'un encadrement professionnel. En plus, elles ont la possibilité de participer à diverses activités qui leur permettent de garder une vie sociale et d\'éviter la solitude. Dans certains cas, c\'est mieux que de rester seules chez elles. (Sophie, infirmière)'],
                    ['title' => 'Document 2', 'content' => 'Les maisons de retraite peuvent priver les personnes âgées de la présence de leur famille et donner l\'impression d\'être abandonnées. De plus, les conditions de vie ne sont pas toujours satisfaisantes et certains établissements manquent parfois de personnel compétent. Selon moi, l\'aide à domicile est une meilleure solution pour vieillir auprès de ses proches. (Jean, retraité)'],
                ],
                'correction' => "Maisons de retraite : solution idéale ou isolement forcé ?\n\nLe Document 1 met en avant les avantages des maisons de retraite, notamment l'accompagnement médical et les activités sociales qui réduisent l'isolement des personnes âgées. En revanche, le Document 2 souligne les aspects négatifs, comme l'éloignement familial et le manque de personnel qualifié dans certains établissements, plaidant ainsi pour un maintien à domicile.\n\nÀ mon avis, les deux documents apportent des arguments pertinents. Les maisons de retraite garantissent une sécurité médicale et permettent aux personnes âgées de garder une vie sociale, ce qui est essentiel pour leur bien-être. Cependant, le Document 2 rappelle justement que l'éloignement familial peut créer un sentiment d'abandon. Pour moi, la meilleure solution est de privilégier le maintien à domicile tant que c'est possible, tout en gardant la maison de retraite comme une alternative pour les situations de dépendance lourde. Ainsi, on peut concilier soins adaptés et proximité familiale.",
            ],
        ],
    ],
    [
        'combo' => 2,
        'tasks' => [
            [
                'task' => 1,
                'prompt' => 'Rédigez un message à votre ami Cédric pour lui fournir des instructions concernant l\'entretien de votre maison et de votre jardin pendant votre absence.',
                'correction' => "Salut Cédric,\n\nMerci encore d'avoir accepté de garder ma maison et mon jardin pendant mes vacances. Voici ce que tu dois faire : veille à ce que les portes et fenêtres soient bien fermées chaque soir. Pour le jardin, arrose les plantes tous les deux jours, surtout en cas de forte chaleur. Le système de chauffage est à éteindre le matin et à remettre en marche en fin d'après-midi si nécessaire. N'oublie pas de récupérer le courrier dans la boîte aux lettres. Si tu as des questions, n'hésite pas à me contacter.\n\nJe compte sur toi, merci encore !\n\nÀ bientôt,\nelite tcf canada",
            ],
            [
                'task' => 2,
                'prompt' => 'Rédigez une lettre de réclamation pour exprimer votre insatisfaction à l\'égard des services fournis par une agence de voyage suite à une organisation défaillante de votre séjour.',
                'correction' => "Voyage raté : méfiez-vous des agences peu sérieuses !\n\nPartir en voyage est censé être une expérience inoubliable, pleine de découvertes et de détente. Pour éviter le stress de l'organisation, de nombreux voyageurs font appel à des agences spécialisées. Pourtant, toutes ne tiennent pas leurs promesses, et un mauvais choix peut transformer des vacances de rêve en cauchemar.\n\nC'est exactement ce qui m'est arrivé. L'agence nous avait garanti un séjour tout compris avec hébergement de qualité et excursions bien organisées. À notre arrivée, l'hôtel était vétuste, les prestations insuffisantes et certaines excursions annulées sans explication. Pire encore, le service client était inexistant, rendant toute réclamation impossible.\n\nSi vous envisagez de passer par une agence, prenez le temps de lire les avis et vérifiez les garanties offertes. Privilégiez les agences réputées et exigez un contrat détaillé. Un voyage réussi commence par une organisation fiable !",
            ],
            [
                'task' => 3,
                'prompt' => 'La restauration rapide',
                'documents' => [
                    ['title' => 'Document 1', 'content' => 'Les restaurants de restauration rapide offrent une gamme variée de plats équilibrés tout en respectant les normes d\'hygiène. Le client, ayant la liberté de composer son propre menu, assume ainsi la responsabilité de ses choix alimentaires.'],
                    ['title' => 'Document 2', 'content' => 'La consommation fréquente de restauration rapide peut avoir des effets néfastes sur la santé, contribuant à l\'apparition de problèmes graves et irréversibles tels que l\'obésité et d\'autres maladies associées.'],
                ],
                'correction' => "Restauration rapide : alliée du quotidien ou menace pour la santé ?\n\nLa restauration rapide divise l'opinion. Le Document 1 met en avant la diversité des plats proposés et le respect des normes d'hygiène. Selon lui, les clients restent responsables de leurs choix alimentaires. En revanche, le Document 2 souligne les effets négatifs sur la santé, notamment le risque d'obésité lié à une alimentation trop riche et déséquilibrée.\n\nÀ mon avis, la restauration rapide peut être une solution pratique, mais elle doit être consommée avec modération. Les enseignes proposent aujourd'hui des options plus saines, permettant un équilibre alimentaire. Toutefois, le danger réside dans une consommation excessive de produits transformés, souvent trop gras ou sucrés. Les jeunes, particulièrement exposés, doivent être sensibilisés aux risques d'une mauvaise alimentation. Privilégier les ingrédients frais et limiter les excès est essentiel pour préserver la santé. Plutôt que de la condamner, mieux vaut encourager une approche équilibrée, combinant plaisir et nutrition responsable.",
            ],
        ],
    ],
    [
        'combo' => 3,
        'tasks' => [
            [
                'task' => 1,
                'prompt' => 'Parc de loisirs : J\'ai hâte de profiter de cette journée avec toi demain ! Peux-tu me dire quelles activités sont au programme ? Écrivez un message pour répondre à votre ami(e).',
                'correction' => "Salut !\n\nJe suis super excité pour demain aussi ! Au parc de loisirs, on commencera par une petite balade dans le parc d'aventure. Ensuite, on pourra essayer la grande roue, histoire de profiter de la vue ! Si ça te dit, on ira aussi tester les montagnes russes et la salle de jeux. On pourra finir par un tour de bateau, c'est toujours relaxant.\n\nJe pense que ça va être une journée géniale, prépare-toi à t'amuser !\n\nÀ demain !\nelite tcf canada",
            ],
            [
                'task' => 2,
                'prompt' => 'Vous avez publié une annonce en ligne pour louer votre appartement. Rédigez un courriel afin de fournir des informations sur le logement et le quartier.',
                'correction' => "Mon appartement à louer : Confort et emplacement idéal\n\nBonjour,\n\nJe vous écris pour vous donner plus de détails sur l'appartement que je propose à la location. Il s'agit d'un deux pièces de 60 m², situé au troisième étage d'un immeuble calme. L'appartement se compose d'une chambre, d'un salon spacieux, d'une cuisine équipée et d'une salle de bain moderne. Il dispose également d'un balcon avec une belle vue.\n\nL'emplacement est idéal, en plein cœur de la ville. Vous trouverez des transports en commun (métro et bus) à proximité, ainsi que de nombreux commerces, restaurants et parcs. Ce quartier est parfait pour ceux qui veulent vivre dans un environnement dynamique et pratique.\n\nSi vous êtes intéressé, n'hésitez pas à me contacter pour plus d'informations ou pour planifier une visite.\n\nCordialement,\nNabil",
            ],
            [
                'task' => 3,
                'prompt' => 'Faire ses courses alimentaires chez les producteurs locaux ou au supermarché',
                'documents' => [
                    ['title' => 'Document 1', 'content' => 'Jean qui vit à la campagne favorise l\'achat des produits alimentaires directement à la ferme pour la bonne qualité, quitte à payer un peu plus cher.'],
                    ['title' => 'Document 2', 'content' => 'Camille qui vit dans la ville préfère faire ses courses au supermarché pour la variété qu\'il propose et pour les prix abordables.'],
                ],
                'correction' => "Le Choix des Courses : Producteurs Locaux ou Supermarché ?\n\nDans le débat sur les courses alimentaires, producteurs locaux et supermarchés s'opposent. Le Document 1 met en avant la qualité des produits achetés directement à la ferme, bien que leur prix soit plus élevé. À l'inverse, le Document 2 défend la diversité et l'accessibilité des produits en supermarché, soulignant un critère économique important.\n\nÀ mon sens, chaque mode d'achat présente des avantages distincts. Acheter chez les producteurs locaux garantit des produits frais et soutient l'agriculture locale, favorisant ainsi une consommation plus responsable. Cependant, le Document 2 souligne avec raison l'attractivité des supermarchés, qui offrent un large choix à des prix souvent plus compétitifs. La praticité des grandes surfaces, notamment en milieu urbain, est indéniable. Plutôt que de les opposer, je préconise une complémentarité entre les deux : privilégier les producteurs locaux pour certains produits frais tout en profitant de la diversité des supermarchés pour le reste. Cette approche permet de concilier qualité, accessibilité et engagement en faveur des circuits courts.",
            ],
        ],
    ],
    [
        'combo' => 4,
        'tasks' => [
            [
                'task' => 1,
                'prompt' => 'Invitez votre ami(e) à venir passer les vacances chez vous. Dans votre message, décrivez les sites touristiques et les endroits intéressants à découvrir dans votre ville.',
                'correction' => "Salut Jean,\n\nJ'espère que tu vas bien ! J'aimerais t'inviter à passer tes vacances dans ma ville. C'est un endroit magnifique avec beaucoup à offrir : des plages splendides, des restaurants délicieux, et une vie nocturne animée. Je te ferai découvrir les meilleurs coins et les petites merveilles cachées. Ce serait génial de passer du temps ensemble et de te montrer pourquoi j'aime tant cet endroit. J'ai hâte de te voir ici !\n\nÀ bientôt,\nelite tcf canada",
            ],
            [
                'task' => 2,
                'prompt' => 'Vous avez été sélectionné(e) pour un concours où le prix est un séjour de deux semaines dans votre ville favorite. Le thème du concours était "Mon artiste préféré". Rédigez un article de blog pour parler de l\'artiste que vous aimez le plus.',
                'correction' => "Mon Artiste Préféré : Vincent Van Gogh\n\nRécemment, j'ai participé à un concours pour gagner un séjour de deux semaines dans ma ville préférée. Le thème était « Mon artiste préféré ». J'ai choisi Vincent Van Gogh, dont l'œuvre m'inspire profondément.\n\nVan Gogh est célèbre pour ses œuvres emblématiques comme « La Nuit étoilée » et « Les Tournesols ». Son utilisation des couleurs et ses techniques uniques captivent mon imagination. Dans mon article, j'ai décrit ma visite au Musée Van Gogh à Amsterdam, où j'ai eu la chance d'admirer ses œuvres de près. C'était une expérience inoubliable qui a renforcé mon admiration pour son art.\n\nJe recommande à tous les amateurs d'art de découvrir les œuvres de Van Gogh. Sa capacité à transmettre des émotions à travers ses peintures est extraordinaire et offre une perspective unique sur la beauté du monde.",
            ],
            [
                'task' => 3,
                'prompt' => 'La chasse aux animaux : pour ou contre ?',
                'documents' => [
                    ['title' => 'Document 1', 'content' => 'Je suis de ceux qui n\'arrivent pas à comprendre comment l\'on peut prendre du plaisir à tuer des animaux. Je suis de ceux qui n\'arrivent pas à comprendre comment on peut prétendre aimer la nature alors qu\'on la détruit.'],
                    ['title' => 'Document 2', 'content' => 'Les gens chassent pour différentes raisons : la subsistance, le commerce, la conservation et l\'aménagement de la faune, la protection de la propriété, l\'exercice, le loisir et le prestige.'],
                ],
                'correction' => "Chasse aux Animaux : Passion ou Destruction ?\n\nDans le débat sur la chasse, les opinions divergent. Le Document 1 exprime une opposition ferme, soulignant le paradoxe de prétendre aimer la nature tout en la détruisant. À l'inverse, le Document 2 met en lumière les diverses motivations derrière la pratique de la chasse.\n\nÀ mon sens, chaque point de vue présente des aspects importants. Les opposants à la chasse soulignent un respect profond pour la vie animale et la nature, refusant toute forme de violence. Cependant, le Document 2 défend la chasse comme une pratique multifacette, incluant la subsistance, la gestion de la faune et le loisir. Plutôt que de condamner ou d'approuver unilatéralement, il est crucial de considérer les contextes culturels et économiques spécifiques. La diversité des perspectives peut mener à des solutions équilibrées, respectant à la fois les besoins humains et la protection de la faune.",
            ],
        ],
    ],
    [
        'combo' => 8,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Votre ami Cédric a accepté de garder votre maison et jardin pendant vos vacances. Écrivez un message pour lui dire ce qu\'il doit faire.', 'correction' => "Salut Cédric,\n\nMerci encore d'avoir accepté de garder ma maison et mon jardin pendant mes vacances. Voici ce que tu dois faire : veille à ce que les portes et fenêtres soient bien fermées chaque soir. Pour le jardin, arrose les plantes tous les deux jours, surtout en cas de forte chaleur. Le système de chauffage est à éteindre le matin et à remettre en marche en fin d'après-midi si nécessaire. N'oublie pas de récupérer le courrier dans la boîte aux lettres. Si tu as des questions, n'hésite pas à me contacter.\n\nJe compte sur toi, merci encore !\n\nÀ bientôt,\nNabil"],
            ['task' => 2, 'prompt' => 'Vous faites une réclamation par rapport aux mauvaises prestations d\'une agence de voyages suite à un voyage mal organisé. Exprimez votre mécontentement.', 'correction' => "Voyage raté : méfiez-vous des agences peu sérieuses !\n\nPartir en voyage est censé être une expérience inoubliable, pleine de découvertes et de détente. Pour éviter le stress de l'organisation, de nombreux voyageurs font appel à des agences spécialisées. Pourtant, toutes ne tiennent pas leurs promesses, et un mauvais choix peut transformer des vacances de rêve en cauchemar.\n\nC'est exactement ce qui m'est arrivé. L'agence nous avait garanti un séjour tout compris avec hébergement de qualité et excursions bien organisées. À notre arrivée, l'hôtel était vétuste, les prestations insuffisantes et certaines excursions annulées sans explication. Pire encore, le service client était inexistant, rendant toute réclamation impossible.\n\nSi vous envisagez de passer par une agence, prenez le temps de lire les avis et vérifiez les garanties offertes. Privilégiez les agences réputées et exigez un contrat détaillé. Un voyage réussi commence par une organisation fiable !"],
            ['task' => 3, 'prompt' => 'La Restauration Rapide.', 'documents' => [['title' => 'Document 1', 'content' => 'Les restaurants rapides se distinguent par leur engagement à proposer une variété de plats équilibrés, respectant strictement les normes d\'hygiène. En laissant aux clients la liberté de composer leur propre menu, ces établissements les responsabilisent dans leurs choix alimentaires, tout en satisfaisant leurs préférences gustatives.'], ['title' => 'Document 2', 'content' => 'Les spécialistes affirment que manger régulièrement dans des restaurants de fast-food, qui proposent de la restauration rapide, est dangereux pour la santé. La nourriture servie est souvent la même : frites, hamburgers et boissons sucrées. Ces aliments contiennent une grande quantité de calories, bien trop pour un seul repas. De plus, la plupart des produits dans ces restaurants sont emballés dans du plastique. Par conséquent, manger dans un fast-food augmente la production de déchets plastiques, ce qui est nuisible pour l\'environnement.']], 'correction' => "Restauration rapide : alliée du quotidien ou menace pour la santé ?\n\nLa restauration rapide divise l'opinion. Le Document 1 met en avant la diversité des plats proposés et le respect des normes d'hygiène. Selon lui, les clients restent responsables de leurs choix alimentaires. En revanche, le Document 2 souligne les effets négatifs sur la santé, notamment le risque d'obésité lié à une alimentation trop riche et déséquilibrée.\n\nÀ mon avis, la restauration rapide peut être une solution pratique, mais elle doit être consommée avec modération. Les enseignes proposent aujourd'hui des options plus saines, permettant un équilibre alimentaire. Toutefois, le danger réside dans une consommation excessive de produits transformés, souvent trop gras ou sucrés. Les jeunes, particulièrement exposés, doivent être sensibilisés aux risques d'une mauvaise alimentation. Privilégier les ingrédients frais et limiter les excès est essentiel pour préserver la santé. Plutôt que de la condamner, mieux vaut encourager une approche équilibrée, combinant plaisir et nutrition responsable."],
        ],
    ],
    [
        'combo' => 9,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Répondez au courriel de votre ami Lucas pour lui donner des informations sur les nouveaux locaux de votre entreprise (lieu, disposition des pièces, équipements, etc.)', 'correction' => "Salut Lucas,\n\nJe voulais te tenir au courant de nos nouveaux locaux. Nous sommes désormais situés au 123 Rue de la République. Les bureaux sont modernes et spacieux, avec des espaces ouverts et lumineux. Nous avons une grande salle de réunion équipée des dernières technologies, un coin détente avec café et snacks, et même une salle de sport pour le personnel. Tout est pensé pour favoriser la productivité et le bien-être.\n\nJ'ai hâte de te les faire visiter !\n\nÀ bientôt,\nNabil"],
            ['task' => 2, 'prompt' => 'Vous avez assisté à un événement intitulé « Une semaine sans voiture ». Racontez votre expérience et donnez votre impression sur cette initiative. Décrivez le déroulement de l\'événement (dates, lieu, activités proposées).', 'correction' => "Une Semaine Sans Voiture : Une Expérience Écoresponsable\n\nLa semaine dernière, j'ai participé à l'événement « Une semaine sans voiture » du 20 au 26 juillet dans notre ville. L'initiative visait à encourager les habitants à laisser leurs voitures à la maison et à explorer des modes de transport plus écologiques. Des ateliers sur le vélo, des randonnées urbaines et des conférences sur la mobilité durable étaient au programme.\n\nPersonnellement, j'ai adoré cette expérience. J'ai redécouvert ma ville à pied et à vélo, ce qui m'a permis de voir des endroits que je n'avais jamais remarqués. Les ateliers de réparation de vélos étaient particulièrement utiles, et les discussions sur l'impact environnemental des voitures ont été enrichissantes.\n\nJe recommande vivement cette initiative à tous. C'est une excellente manière de réduire notre empreinte carbone tout en découvrant des alternatives de transport plus saines et économiques."],
            ['task' => 3, 'prompt' => 'Les vêtements de grande marque', 'documents' => [['title' => 'Document 1', 'content' => 'Les vêtements de marque sont très importants pour les enfants et les adolescents. C\'est un moyen de s\'exprimer et de se rattacher à un groupe social. Cette attirance pour les marques est très présente chez les adolescents qui se cherchent et montrent leur personnalité. Les enfants aiment également porter des vêtements de marque avec des images de dessins animés qu\'ils regardent ou des logos qu\'ils apprécient.'], ['title' => 'Document 2', 'content' => 'Les enfants grandissent très vite et les vêtements sont portés pendant une courte période. Ainsi, les vêtements deviennent rapidement trop petits. Mais il y a aussi le fait que les enfants usent assez rapidement les vêtements en jouant à l\'extérieur avec les copains, en s\'amusant dans l\'herbe ou à l\'aire de jeux. Les habits sont très vite sales ou troués.']], 'correction' => "Vêtements de Marque : Entre Expression et Praticité\n\nDans le débat sur les vêtements de marque, deux perspectives s'opposent. Le Document 1 valorise l'importance des marques pour les enfants et adolescents comme moyen d'expression et d'appartenance sociale. En revanche, le Document 2 met en avant la rapidité avec laquelle les enfants grandissent et usent leurs vêtements.\n\nÀ mon avis, chaque point de vue présente des arguments valides. Les vêtements de marque offrent aux jeunes une manière de s'exprimer et de se sentir intégrés à un groupe. Toutefois, comme le souligne le Document 2, la croissance rapide des enfants et leur tendance à user leurs vêtements rapidement remettent en question la durabilité de ces achats. Plutôt que d'opposer ces deux points de vue, je suggère une approche équilibrée : acheter des vêtements de marque pour des occasions spéciales tout en privilégiant des options plus économiques pour un usage quotidien. Cette solution permet aux enfants de profiter de l'expression personnelle offerte par les marques tout en restant pragmatique face à la nature éphémère de leurs besoins vestimentaires."],
        ],
    ],
    [
        'combo' => 10,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous avez décidé d\'offrir un voyage à votre ami pour son anniversaire. Écrivez un message pour lui expliquer ce que vous avez préparé : la destination, les dates et les autres détails du voyage.', 'correction' => "Salut Maxime,\n\nJe voulais te prévenir que j'ai réservé un voyage pour ton anniversaire ! Nous partons à Paris, du 15 au 22 mai. J'ai tout organisé : vols, hébergement et même quelques activités sympas à faire sur place. Je suis vraiment impatient que tu découvres tout ça ! Il me tarde qu'on passe ce moment ensemble et que tu te détendes pleinement. Prépare-toi à vivre une aventure incroyable !\n\nÀ très bientôt pour plus de détails !\n\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Un internaute exprime des inquiétudes concernant son départ pour étudier à l\'étranger. Partagez votre expérience personnelle sur les défis rencontrés, les solutions trouvées et les bénéfices tirés de cette expérience.', 'correction' => "Partir étudier à l'étranger : une peur qui en vaut la peine !\n\nÉtudier à l'étranger, c'est sortir de sa zone de confort pour découvrir une nouvelle culture, apprendre différemment et gagner en autonomie. Cela peut faire peur, mais cette peur est normale.\n\nQuand je suis parti un an en Italie, j'étais stressé. Je ne maîtrisais pas la langue et je craignais la solitude. Pourtant, j'ai vite compris qu'il fallait agir : j'ai pris des cours, participé à des activités étudiantes et rencontré d'autres jeunes. Peu à peu, je me suis senti intégré et plus confiant.\n\nAujourd'hui, je garde un souvenir inoubliable de cette aventure. J'ai progressé sur tous les plans : personnel, social et académique.\n\nSi tu hésites à partir, n'aie pas peur. Tu reviendras transformé, plus riche et plus ouvert."],
            ['task' => 3, 'prompt' => 'La réduction du temps de travail', 'documents' => [['title' => 'Document 1', 'content' => 'La réduction du temps de travail permet aux employés de mieux équilibrer leur vie professionnelle et personnelle. En travaillant moins, ils peuvent consacrer plus de temps à leur famille, à leurs loisirs et à leur santé. Cela peut également augmenter leur satisfaction au travail et réduire le stress, améliorant ainsi leur productivité globale.'], ['title' => 'Document 2', 'content' => 'Réduire les heures de travail peut aider les entreprises en réduisant l\'absentéisme et en augmentant la fidélisation des employés. En offrant des horaires plus flexibles, les employés sont généralement plus motivés et impliqués. Cependant, cela nécessite une organisation efficace et une adaptation des processus pour maintenir la productivité et répondre aux besoins de l\'entreprise.']], 'correction' => "Travailler Moins Pour Vivre Mieux ?\n\nLa question de la réduction du temps de travail suscite un vif débat. Le Document 1 insiste sur ses effets bénéfiques pour les salariés, comme une meilleure qualité de vie et une baisse du stress. Le Document 2, quant à lui, met en avant les avantages pour l'entreprise, tout en soulignant les défis d'organisation.\n\nÀ mon avis, réduire le temps de travail peut être une mesure gagnante à condition d'être bien encadrée. Les bénéfices humains sont clairs : un salarié moins stressé est plus engagé, plus créatif et donc plus productif. Du côté des entreprises, cette démarche favorise la fidélisation et limite les arrêts maladie. Néanmoins, pour que cela fonctionne, il faut repenser les méthodes de travail, répartir les tâches différemment et investir dans une meilleure coordination. Ainsi, la réduction du temps de travail peut véritablement concilier bien-être et performance."],
        ],
    ],
    [
        'combo' => 11,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous souhaitez fêter votre anniversaire dans un restaurant. Vous invitez vos amis. Vous leur écrivez un courriel pour leur donner toutes les informations nécessaires (lieu, date, menu, prix, etc.) et vous leur demandez une réponse.', 'correction' => "Chers amis,\n\nJ'espère que ce message vous trouve en pleine forme. Pour célébrer mon anniversaire cette année, je vous invite tous à me rejoindre au restaurant « Délices de Fès » à Fès. La soirée aura lieu le samedi 15 juillet à 19h30.\n\nLe menu proposé comprendra une sélection variée de plats traditionnels marocains, ainsi que des options végétariennes. Le prix par personne est de 300 MAD, boissons non comprises.\n\nMerci de bien vouloir confirmer votre présence avant le 5 juillet pour que je puisse finaliser la réservation.\n\nDans l'attente de vous retrouver pour partager ce moment spécial ensemble !\n\nBien amicalement,\nNabil"],
            ['task' => 2, 'prompt' => 'Vous avez quitté la ville afin de vous installer à la campagne. Sur votre blog, vous expliquez pourquoi vous avez fait ce choix et vous présentez les avantages de votre nouvelle vie.', 'correction' => "Une Nouvelle Vie au Vert : Pourquoi J'ai Choisi la Campagne\n\nIl y a quelques mois, j'ai pris une grande décision : quitter l'effervescence de la ville pour le calme de la campagne. Ce changement de vie, bien réfléchi, a transformé mon quotidien. Mais pourquoi ce choix ? Et quels sont les bienfaits que j'en retire ?\n\nHabiter en ville offrait confort et opportunités, mais le rythme effréné et le bruit constant devenaient pesants. En m'installant à la campagne, j'ai découvert un cadre apaisant, un air plus pur et une proximité avec la nature qui m'avait tant manqué. Je me suis aussi rapproché des habitants, toujours accueillants, et j'ai retrouvé une alimentation locale et savoureuse.\n\nSi vous aspirez à plus de sérénité et de simplicité, je vous invite à envisager ce mode de vie. La campagne offre une qualité de vie incomparable, idéale pour se ressourcer. Essayez, vous serez conquis !"],
            ['task' => 3, 'prompt' => 'Les Caméras De Surveillance À L\'école : Pour Ou Contre ?', 'documents' => [['title' => 'Document 1', 'content' => 'Dans l\'école où j\'enseigne à Montréal, les caméras de surveillance sont omniprésentes. Leur présence permet de dissuader les élèves de commettre des actes de violence. Les enseignants, les parents et la majorité des élèves les acceptent volontiers, car ils se sentient rassurés quant à la sécurité des enfants et cela permet aux enseignants de travailler dans de bonnes conditions. Toutefois, certains élèves considèrent que cela porte atteinte à leur vie privée.'], ['title' => 'Document 2', 'content' => 'Je suis opposé à l\'installation des caméras de surveillance dans nos écoles à Montréal. Les résultats obtenus dans les pays où ce système est utilisé ne sont pas convaincants. Les personnes mal intentionnées peuvent facilement contourner les caméras, qui sont très visibles. Les problèmes de discipline dans une école peuvent être résolus en améliorant la communication entre les enseignants, l\'administration et les élèves. Il est également nécessaire de faire respecter et expliquer les règles de l\'école par tous, plutôt que de recourir aux caméras.']], 'correction' => "Caméras de Surveillance à l'École : Sécurité ou Intrusion ?\n\nLe débat sur l'installation des caméras de surveillance dans les écoles divise. Le Document 1 insiste sur leur rôle dans la prévention de la violence et la sécurité des élèves, une opinion partagée par de nombreux parents et enseignants. Toutefois, le Document 2 critique leur efficacité et préconise un dialogue renforcé pour résoudre les problèmes.\n\nÀ mon sens, bien que les caméras puissent dissuader certaines violences, elles ne résolvent pas les problèmes de fond. Leur impact sur la vie privée des élèves est préoccupant, et leur efficacité reste limitée face aux comportements réellement malveillants. Une école sûre repose avant tout sur la communication et le respect des règles. Plutôt que de se fier uniquement à la surveillance, investir dans des programmes éducatifs, des formations pour le personnel et des échanges réguliers entre élèves, enseignants et parents serait une approche plus équilibrée."],
        ],
    ],
    [
        'combo' => 12,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Rédigez un message à un ami pour l\'inviter à une rencontre avec un écrivain organisée par la bibliothèque de votre ville.', 'correction' => "Salut Denis !\n\nJe voulais te parler d'un super événement qui se passe à la bibliothèque de notre ville. Ils organisent une rencontre avec un écrivain le 20 Février, et je pense que ça pourrait vraiment t'intéresser ! Ce sera l'occasion d'échanger avec lui, de découvrir son travail et peut-être même de lui poser des questions. En plus, l'ambiance est toujours sympa lors de ces rencontres.\n\nTu serais partant pour y aller ensemble ?\n\nA très vite,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Rédigez un article de blog relatant votre expérience lors de l\'événement « La Semaine du Goût », auquel vous avez participé.', 'correction' => "Plongée dans les saveurs : mon expérience à La Semaine du Goût\n\nLa Semaine du Goût est un événement incontournable pour les amateurs de gastronomie. Pendant une semaine, cet événement offre l'opportunité de découvrir des produits locaux, participer à des ateliers et assister à des dégustations. C'est un véritable voyage sensoriel où chaque participant peut approfondir ses connaissances culinaires.\n\nJ'ai eu la chance de participer à plusieurs ateliers interactifs. L'un des moments forts fut la dégustation de produits du terroir accompagnée de conseils de chefs pour sublimer les saveurs. J'ai aussi appris à marier certains ingrédients, un savoir-faire que je vais intégrer dans ma cuisine.\n\nSi vous êtes passionné par la cuisine et la découverte de nouveaux goûts, je vous recommande vivement de participer à La Semaine du Goût. C'est une expérience enrichissante et conviviale, parfaite pour affiner vos connaissances et éveiller vos papilles."],
            ['task' => 3, 'prompt' => 'L\'art Urbain : Pour Ou Contre ?', 'documents' => [['title' => 'Document 1', 'content' => 'Grâce à l\'art, la curiosité des citadins est attisée dans l\'espace urbain. Que ce soit par une peinture ou un spectacle de rue, l\'atmosphère éphémère ainsi créée offre une interaction entre des artistes peu connus et un public hétéroclite, parfois peu habitué à côtoyer cette forme d\'art. Les villes d\'aujourd\'hui n\'ont plus la même vocation que celles d\'hier. Plus qu\'un lieu de résidence, la ville se réinvente, s\'enrichit de la diversité de sa population, s\'agence différemment et s\'ouvre sur le monde. Les espaces verts se créent et les murs se parent de couleurs grâce au street art. Cela débouche sur des lieux où la qualité de vie est privilégiée, tout en respectant la nature et l\'environnement.'], ['title' => 'Document 2', 'content' => 'Mais à une plus large échelle, cela n\'est pas aussi évident. Les graffitis peuvent être perçus comme une dégradation de la communauté, une pollution visuelle ou une preuve de la rupture sociale. On les considère comme du vandalisme qui défigure les biens publics. Le débat sur les avantages et les inconvénients des graffitis fait rage parmi les artistes, les législateurs et les membres de la communauté.']], 'correction' => "L'art urbain : expression artistique ou vandalisme ?\n\nL'art urbain transforme l'espace public et suscite le débat. Le Document 1 valorise son impact positif en embellissant les villes et en favorisant l'interaction entre artistes et passants. À l'inverse, le Document 2 souligne les critiques liées aux graffitis, perçus comme une forme de vandalisme qui détériore les biens publics.\n\nÀ mon sens, l'art urbain représente une richesse culturelle qui dynamise l'environnement urbain et le rend plus accessible. Toutefois, il est crucial de distinguer les œuvres artistiques des actes de dégradation. Certaines fresques embellissent les murs et véhiculent des messages forts, tandis que d'autres inscriptions nuisent à l'esthétique des lieux. Pour concilier créativité et respect des espaces publics, les villes devraient encadrer ces pratiques en définissant des zones dédiées aux artistes. Plutôt qu'une interdiction totale, une régulation adaptée favoriserait un art urbain harmonieux, contribuant à la culture, au tourisme et à l'embellissement des villes."],
        ],
    ],
    [
        'combo' => 13,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Rédigez un message à un ami pour l\'informer de votre déménagement et lui demander son aide, en précisant la date, le lieu et le déroulement du programme.', 'correction' => "Salut Jacques !\n\nJ'espère que tu vas bien ! J'ai une grande nouvelle : je déménage dans mon nouveau logement le 25 février et j'aurais vraiment besoin de ton aide. Le déménagement se fera à l'adresse suivante : 123 Rue de l'Exemple, et je commence à tout emballer la veille, soit le 24 février. Ce serait top si tu pouvais m'aider à transporter les cartons et à installer quelques meubles. On pourrait même faire une petite pause après pour se détendre et célébrer ce nouveau départ !\n\nMerci beaucoup, et j'espère que tu seras dispo !\n\nA très vite,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Rédigez un article de blog sur votre artiste préféré dans le cadre d\'un concours dont le thème est « Mon artiste préféré », permettant de gagner un séjour de deux semaines dans votre ville favorite.', 'correction' => "Pourquoi j'admire autant Stromae ?\n\nL'art a ce pouvoir unique de nous toucher et de nous inspirer. Parmi les nombreux artistes talentueux, Stromae occupe une place spéciale pour moi. Son style mélange électro, pop et rap, et ses textes profonds abordent des thèmes de société comme la solitude et les relations humaines.\n\nDès ma première écoute, j'ai été captivé par son univers. Ses chansons racontent des histoires touchantes, alliant mélodies entraînantes et paroles percutantes. « Papaoutai » ou « Formidable » sont des titres qui m'ont particulièrement marqué. C'est pour cette raison que j'ai choisi Stromae pour participer à un concours sur mon artiste préféré !\n\nSi vous ne connaissez pas encore Stromae, je vous invite à découvrir ses albums. Son talent et son originalité ne manqueront pas de vous séduire et de vous faire réfléchir !"],
            ['task' => 3, 'prompt' => 'Les objets connectés', 'documents' => [['title' => 'Document 1', 'content' => 'Les objets intelligents rendent notre quotidien plus pratique. Ce sont des appareils qui peuvent être contrôlés à distance par un téléphone ou Internet, comme le chauffage ou les systèmes de sécurité de la maison. Par ailleurs, des objets tels que les montres ou bracelets connectés suivent nos activités et nous motivent à faire plus d\'exercice, en mesurant par exemple nos pas. Leur utilité est particulièrement notable dans le domaine de la santé. Certains objets agissent comme un assistant santé, nous rappelant les rendez-vous médicaux ou la prise de nos médicaments.'], ['title' => 'Document 2', 'content' => 'On estime qu\'il y aurait 50 milliards d\'objets intelligents dans le monde, tels que des alarmes, des téléviseurs, des caméras de surveillance, des volets ou des détecteurs de fumée, entre autres. Avec cette expansion, la question de la sécurité devient cruciale. En effet, un hacker pourrait prendre le contrôle de ces appareils en quelques minutes. Par exemple, un cambrioleur pourrait, grâce aux caméras de surveillance connectées, vérifier si les habitants sont absents avant de commettre un cambriolage. Il est même possible d\'accéder au système connecté d\'une voiture et de la contrôler à distance.']], 'correction' => "Objets connectés : progrès technologique ou danger invisible ?\n\nLes objets connectés révolutionnent notre quotidien. Le Document 1 insiste sur leur aspect pratique, permettant de contrôler à distance divers équipements et d'améliorer notre bien-être. Ils facilitent aussi la surveillance de la santé. En revanche, le Document 2 alerte sur les risques liés à la cybersécurité, notamment le piratage et l'utilisation malveillante de ces technologies.\n\nÀ mon avis, les objets connectés sont une avancée majeure, mais leur utilisation doit être sécurisée. Ils offrent un confort indéniable, optimisant nos habitudes et renforçant la prévention médicale. Cependant, les risques de piratage sont bien réels, mettant en péril la vie privée et la sécurité des utilisateurs. Pour éviter ces dangers, il est essentiel de sensibiliser les consommateurs aux bonnes pratiques numériques et de renforcer la protection des données. Plutôt que de les rejeter, il faut adopter une approche équilibrée, alliant innovation et vigilance."],
        ],
    ],
    [
        'combo' => 14,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous êtes locataire d\'un appartement qui vous semble trop grand. Rédigez une annonce dans un journal pour trouver un colocataire, en indiquant la superficie, le profil recherché et le montant du loyer, entre autres détails.', 'correction' => "À LOUER – Recherche de Colocataire\n\nAppartement lumineux à partager, trop spacieux pour un seul occupant! Situé en plein cœur de la ville, ce logement de 80m² offre confort et tranquillité. Je cherche un(e) colocataire calme et responsable, respectueux(se) de l'espace commun. Prix raisonnable incluant toutes charges. Idéal pour étudiant(e) ou jeune professionnel(le). Ambiance conviviale et chaleureuse assurée! Contactez-moi pour plus d'informations et visites.\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez récemment débuté une nouvelle activité de loisir, comme un sport ou la danse. Rédigez un article sur votre blog pour partager votre expérience.', 'correction' => "Découverte du Tennis : Une Expérience Enrichissante !\n\nVous cherchez une activité sportive à la fois ludique et dynamique ? Le tennis est un excellent choix ! Ce sport améliore l'endurance, la coordination et la concentration. Accessible à tous, il permet de se défouler tout en s'amusant.\n\nJ'ai récemment commencé le tennis, et dès les premières séances, j'ai adoré ! Au début, manier la raquette et anticiper les balles était un défi, mais avec un peu de pratique, j'ai vite progressé. Chaque échange est un vrai plaisir, et l'esprit compétitif rend le jeu encore plus motivant.\n\nSi vous cherchez une activité sportive complète et conviviale, essayez le tennis ! C'est une belle opportunité de bouger tout en partageant de bons moments. Alors, à vos raquettes !"],
            ['task' => 3, 'prompt' => 'L\'accès gratuit aux musées : avantage ou inconvénient ?', 'documents' => [['title' => 'Document 1', 'content' => 'L\'accès gratuit aux musées peut engendrer une affluence excessive, altérant ainsi la qualité de la visite. De plus, cela risque de diminuer leurs revenus, compromettant l\'entretien des lieux et la conservation des œuvres. Une tarification réduite serait une alternative équilibrée pour favoriser l\'accès à la culture tout en assurant le bon fonctionnement des musées.'], ['title' => 'Document 2', 'content' => 'Rendre les musées gratuits est une excellente initiative, car cela permet à tous d\'accéder à la culture, quel que soit leur revenu. J\'ai eu l\'opportunité de visiter plusieurs musées sans frais, ce qui m\'a permis d\'enrichir mes connaissances sans me préoccuper du coût. À mon avis, la gratuité des musées joue un rôle clé dans l\'éducation du public et la diffusion du patrimoine culturel.']], 'correction' => "Musées Gratuits : Une Bonne Idée ?\n\nLa question de la gratuité des musées oppose deux points de vue. Le Document 1 souligne les risques liés à une entrée libre, comme la surfréquentation et la baisse des revenus nécessaires à la conservation des œuvres. En revanche, le Document 2 met en avant les bénéfices culturels, rendant l'accès aux musées plus équitable et favorisant l'apprentissage pour tous.\n\nÀ mon avis, rendre les musées gratuits est une excellente initiative pour encourager l'accès à la culture, notamment pour les jeunes et les familles aux moyens limités. Toutefois, il est vrai qu'un afflux trop important de visiteurs pourrait nuire à la qualité des expositions et à la préservation des collections. Une solution équilibrée serait d'instaurer la gratuité à certaines périodes ou pour des publics spécifiques, tout en maintenant un tarif réduit pour le reste du temps. Cela permettrait de concilier accessibilité, entretien des musées et préservation des œuvres."],
        ],
    ],
    [
        'combo' => 15,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Votre ami Cédric a accepté de garder votre maison et jardin pendant vos vacances. Écrivez un message pour lui dire ce qu\'il doit faire.', 'correction' => "Salut Cédric,\n\nMerci encore d'avoir accepté de garder ma maison et mon jardin pendant mes vacances. Voici ce que tu dois faire : veille à ce que les portes et fenêtres soient bien fermées chaque soir. Pour le jardin, arrose les plantes tous les deux jours, surtout en cas de forte chaleur. Le système de chauffage est à éteindre le matin et à remettre en marche en fin d'après-midi si nécessaire. N'oublie pas de récupérer le courrier dans la boîte aux lettres. Si tu as des questions, n'hésite pas à me contacter.\n\nJe compte sur toi, merci encore !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Rédigez une lettre de réclamation pour exprimer votre insatisfaction à l\'égard des services fournis par une agence de voyage suite à une organisation défaillante de votre séjour.', 'correction' => "Voyage raté : méfiez-vous des agences peu sérieuses !\n\nPartir en voyage est censé être une expérience inoubliable, pleine de découvertes et de détente. Pour éviter le stress de l'organisation, de nombreux voyageurs font appel à des agences spécialisées. Pourtant, toutes ne tiennent pas leurs promesses, et un mauvais choix peut transformer des vacances de rêve en cauchemar.\n\nC'est exactement ce qui m'est arrivé. L'agence nous avait garanti un séjour tout compris avec hébergement de qualité et excursions bien organisées. À notre arrivée, l'hôtel était vétuste, les prestations insuffisantes et certaines excursions annulées sans explication. Pire encore, le service client était inexistant, rendant toute réclamation impossible.\n\nSi vous envisagez de passer par une agence, prenez le temps de lire les avis et vérifiez les garanties offertes. Privilégiez les agences réputées et exigez un contrat détaillé. Un voyage réussi commence par une organisation fiable !"],
            ['task' => 3, 'prompt' => 'La Restauration Rapide.', 'documents' => [['title' => 'Document 1', 'content' => 'Les restaurants rapides se distinguent par leur engagement à proposer une variété de plats équilibrés, respectant strictement les normes d\'hygiène. En laissant aux clients la liberté de composer leur propre menu, ces établissements les responsabilisent dans leurs choix alimentaires, tout en satisfaisant leurs préférences gustatives.'], ['title' => 'Document 2', 'content' => 'Les spécialistes affirment que manger régulièrement dans des restaurants de fast-food, qui proposent de la restauration rapide, est dangereux pour la santé. La nourriture servie est souvent la même : frites, hamburgers et boissons sucrées. Ces aliments contiennent une grande quantité de calories, bien trop pour un seul repas. De plus, la plupart des produits dans ces restaurants sont emballés dans du plastique. Par conséquent, manger dans un fast-food augmente la production de déchets plastiques, ce qui est nuisible pour l\'environnement.']], 'correction' => "Restauration rapide : alliée du quotidien ou menace pour la santé ?\n\nLa restauration rapide divise l'opinion. Le Document 1 met en avant la diversité des plats proposés et le respect des normes d'hygiène. Selon lui, les clients restent responsables de leurs choix alimentaires. En revanche, le Document 2 souligne les effets négatifs sur la santé, notamment le risque d'obésité lié à une alimentation trop riche et déséquilibrée.\n\nÀ mon avis, la restauration rapide peut être une solution pratique, mais elle doit être consommée avec modération. Les enseignes proposent aujourd'hui des options plus saines, permettant un équilibre alimentaire. Toutefois, le danger réside dans une consommation excessive de produits transformés, souvent trop gras ou sucrés. Les jeunes, particulièrement exposés, doivent être sensibilisés aux risques d'une mauvaise alimentation. Privilégier les ingrédients frais et limiter les excès est essentiel pour préserver la santé. Plutôt que de la condamner, mieux vaut encourager une approche équilibrée, combinant plaisir et nutrition responsable."],
        ],
    ],
    [
        'combo' => 16,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous occupez un grand appartement et recherchez un colocataire. Racontez la manière dont vous imaginez la colocation et présentez les particularités de votre logement.', 'correction' => "Bonjour,\n\nJ'habite dans un grand appartement lumineux de 100 m² situé en centre-ville et je recherche un colocataire sérieux et respectueux. L'appartement comprend trois chambres spacieuses, un grand salon moderne, une cuisine entièrement équipée ainsi qu'un balcon agréable avec vue dégagée. La chambre proposée est meublée et dispose d'un bureau pour travailler. Je souhaite partager une colocation conviviale et calme, où chacun respecte l'intimité de l'autre tout en profitant d'agréables moments ensemble.\nSi vous êtes intéressé(e), n'hésitez pas à me contacter !\n\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Une compagnie de théâtre est venue dans votre ville et vous avez assisté à l\'une de ses représentations. Écrivez un article de blog pour raconter cette expérience.', 'correction' => "Une soirée magique avec la nouvelle troupe de théâtre\n\nLa semaine dernière, une troupe de théâtre itinérante s'est installée dans notre ville et a proposé un spectacle inédit mêlant humour, émotions et musique. Leur objectif est clair : rendre le théâtre accessible à tous et créer un moment de partage unique. L'ambiance était conviviale et l'énergie des comédiens captivait dès les premières minutes.\n\nJ'ai eu la chance d'assister à leur représentation et je dois dire que j'ai été impressionné. Les acteurs jouaient avec naturel et sincérité, les décors étaient simples mais efficaces, et le public riait, applaudissait, parfois même s'émouvait. Ce fut une expérience immersive qui m'a permis d'oublier le quotidien pendant deux heures.\n\nJe recommande vivement à tous ceux qui aiment la culture ou qui veulent simplement passer un bon moment de découvrir cette troupe. Vous ne serez pas déçus !"],
            ['task' => 3, 'prompt' => 'Influence de la publicité sur les enfants : pour ou contre ?', 'documents' => [['title' => 'Document 1', 'content' => 'D\'après une enquête, les enfants sont en permanence confrontés à de nombreuses publicités diffusées à la télévision, dans les journaux ou sur Internet, souvent dans des espaces où ils sont vulnérables. Celles-ci ciblent principalement les jouets, les jeux vidéo et les aliments peu sains, ce qui influence leurs décisions et leurs demandes familiales.'], ['title' => 'Document 2', 'content' => 'Un travail de recherche paru dans une revue scientifique montre que les enfants comprennent difficilement les messages publicitaires, même s\'ils savent généralement que leur but est de persuader. Pourtant, d\'autres facteurs comme l\'éducation reçue des parents, la société et la culture ont un poids plus fort sur leurs choix de consommation que la publicité.']], 'correction' => "Publicité et enfants : manipulation ou simple influence ?\n\nDans le débat sur la publicité destinée aux enfants, les avis divergent. Le Document 1 souligne l'exposition régulière des jeunes aux publicités pour jouets, jeux vidéo ou aliments peu sains, ce qui influence leurs envies et leurs demandes. Le Document 2, en revanche, insiste davantage sur le rôle majeur de l'éducation parentale et sociale.\n\nÀ mon sens, il est indéniable que la publicité exerce un pouvoir sur l'imagination des enfants et peut influencer leurs comportements, surtout face à des messages attractifs et répétitifs. Cependant, comme le souligne le Document 2, la responsabilité incombe aussi aux parents et à l'éducation. Apprendre aux enfants à développer un esprit critique face aux images publicitaires est essentiel. Plutôt que d'interdire complètement la publicité, il serait préférable de la réguler et de promouvoir des contenus adaptés. Ainsi, on protège les enfants tout en favorisant leur autonomie face aux choix de consommation."],
        ],
    ],
    [
        'combo' => 17,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Rédigez un courriel à votre ami francophone afin de solliciter son soutien pour trouver un logement. Pensez à préciser les informations essentielles (genre de logement, budget, date).', 'correction' => "Salut Julien,\n\nJ'espère que tu vas bien. Je t'écris parce que je cherche un logement dans ta ville et j'aurais besoin de ton aide. Je voudrais idéalement un petit appartement meublé avec une chambre et une cuisine équipée. Mon budget est d'environ 500 euros par mois, charges comprises. J'aimerais emménager à partir du 1er octobre. Si tu connais des agences, des annonces ou même des amis qui louent, je serais très reconnaissant que tu me les indiques.\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Votre établissement vous a confié la mission d\'organiser une journée d\'accueil pour les nouveaux étudiants francophones. Écrivez un courriel à leur intention en précisant toutes les informations utiles pour le bon déroulement de cette rencontre.', 'correction' => "Bienvenue aux nouveaux étudiants\n\nNotre école organise une journée spéciale afin de souhaiter la bienvenue aux nouveaux étudiants francophones. Cette activité a pour but de faciliter leur intégration, de leur faire découvrir l'établissement et de créer dès le départ une ambiance conviviale. Ce sera une occasion unique d'échanger, de se connaître et de partager de bons moments.\n\nJ'ai eu la responsabilité d'organiser cette journée et j'ai préparé un programme varié. Le matin, il y aura une visite guidée des locaux (bibliothèque, salles de cours, centre sportif). Ensuite, nous proposerons des ateliers de présentation et des jeux pour encourager la rencontre entre étudiants. L'après-midi sera consacré à un buffet convivial avec de la musique et des animations.\n\nJe recommande vivement à tous les nouveaux étudiants de participer à cette journée. Elle sera une belle opportunité d'intégration et de convivialité."],
            ['task' => 3, 'prompt' => 'La vie à la campagne ou en ville', 'documents' => [['title' => 'Document 1', 'content' => 'Selon moi, vivre en ville offre beaucoup d\'occasions de se divertir : aller au cinéma, manger dans un restaurant, faire les magasins… Tout est accessible sans devoir parcourir de longues distances ni chercher un taxi pour un trajet. On trouve facilement tout ce dont on a besoin. De plus, les amateurs de culture y trouvent aussi leur bonheur : musées, théâtres, opéras… tout est présent !'], ['title' => 'Document 2', 'content' => 'Récemment, j\'ai choisi de quitter la vie urbaine pour m\'installer à la campagne, car je ressentais le besoin de me rapprocher de la nature et de profiter de la tranquillité. Aujourd\'hui, au lieu de sortir chaque jour dans un café ou un restaurant, je préfère inviter mes amis sur ma terrasse ou organiser parfois un barbecue dans mon jardin. Une autre raison qui m\'a poussé à faire ce choix, c\'est le prix des logements : à la campagne, les maisons sont beaucoup plus abordables. Avec mon budget actuel, je profite d\'une grande maison avec terrasse et jardin, alors qu\'en ville je n\'avais qu\'un petit appartement au cinquième étage.']], 'correction' => "Entre gratte-ciel et champs verts : où vivre ?\n\nDans le débat sur le mode de vie, ville et campagne s'opposent. Le Document 1 met en avant les avantages de la vie urbaine : divertissements variés, proximité des services et accès à la culture. En revanche, le Document 2 valorise le calme de la campagne, la nature et surtout le coût plus abordable du logement.\n\nÀ mon sens, chaque environnement possède ses attraits. La ville séduit par sa richesse culturelle, son dynamisme et les nombreuses possibilités qu'elle offre au quotidien. Toutefois, le Document 2 souligne avec raison le bien-être et la tranquillité que procure la campagne. Vivre près de la nature, profiter d'un grand espace extérieur et respirer un air pur représentent un véritable atout pour l'équilibre personnel. Plutôt que d'opposer ces deux modes de vie, je pense que chacun peut choisir selon ses priorités : confort, tranquillité ou dynamisme. Cette liberté d'option permet d'adapter son lieu de vie à ses besoins réels."],
        ],
    ],
    [
        'combo' => 18,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous avez trouvé un appartement intéressant et comptez déménager. Informez un ami par écrit en lui donnant tous les détails essentiels (type de logement, localisation et prix).', 'correction' => "Salut André,\n\nJe voulais te donner une bonne nouvelle : j'ai trouvé un appartement ! Il s'agit d'un logement avec trois pièces : un salon, une chambre et une cuisine équipée. Il est situé dans le centre-ville, proche des commerces et des transports en commun, ce qui est très pratique. Le loyer est de 600 dollars par mois, charges comprises. Je suis vraiment content de cette trouvaille et j'espère pouvoir m'y installer rapidement. Si tu veux, je peux t'envoyer des photos pour que tu le voies.\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez assisté avec un ami à un festival de musique gratuit organisé dans votre ville. Écrivez un article de blog pour partager votre expérience et vos impressions.', 'correction' => "Festival gratuit en ville : une expérience à ne pas manquer !\n\nCe week-end, un festival de musique gratuit s'est tenu dans notre ville. Plusieurs styles étaient proposés : pop, rock, jazz et musique électronique. Des stands de nourriture, des animations et des espaces détente étaient également disponibles, créant une ambiance conviviale et festive pour tous les participants.\n\nJ'y suis allé avec un ami et nous avons passé un moment mémorable. Nous avons découvert des groupes locaux talentueux et dansé au rythme de la musique. L'ambiance était très agréable, et le public enthousiaste a rendu l'expérience encore plus plaisante. Nous avons également profité des stands pour goûter des spécialités locales.\n\nJe recommande vivement ce festival à tous les amateurs de musique. C'est une excellente occasion de découvrir de nouveaux artistes et de profiter d'une journée festive, le tout gratuitement !"],
            ['task' => 3, 'prompt' => 'Diplôme ou expérience pour l\'emploi des jeunes ?', 'documents' => [['title' => 'Document 1', 'content' => 'Beaucoup de jeunes sortant de l\'université se retrouvent sans emploi. La valeur des diplômes sur le marché du travail pose des questions. Souvent, les recruteurs leur reprochent d\'avoir trop étudié et trop peu d\'expérience, ou considèrent leur jeunesse comme un frein. Plus de 60 % des diplômés restent sans travail un an après leurs études. Il paraît donc urgent de mieux reconnaître les diplômes et de faciliter l\'insertion professionnelle.'], ['title' => 'Document 2', 'content' => 'On parle souvent de dirigeants célèbres qui ont réussi sans suivre de cursus universitaire. Ces exemples peuvent laisser penser qu\'il suffit d\'être talentueux pour diriger une entreprise. Certains chefs d\'entreprise considèrent même que l\'université peut freiner la créativité. Selon eux, elle pousse les étudiants à suivre des parcours standards et limite l\'innovation. Pour les futurs entrepreneurs, rien ne remplacerait l\'expérience pratique et l\'autoformation, sans dépendre d\'une institution académique.']], 'correction' => "Diplôme ou expérience : le vrai secret pour réussir ?\n\nDans le débat sur l'emploi des jeunes, diplôme et expérience se confrontent. Le Document 1 souligne les difficultés rencontrées par les jeunes diplômés : chômage élevé, manque d'expérience et jeunesse parfois perçue comme un obstacle. À l'inverse, le Document 2 met en avant le succès de certains dirigeants sans formation universitaire, valorisant l'expérience et l'autoformation.\n\nÀ mon avis, chaque parcours présente des avantages. Les diplômes offrent des connaissances théoriques solides et facilitent l'accès à certaines carrières, répondant aux exigences d'une société où la formation académique reste valorisée. Cependant, le Document 2 rappelle avec justesse que l'expérience pratique et l'autonomie sont essentielles pour développer la créativité et la confiance professionnelle. Acquérir des compétences sur le terrain permet de mieux comprendre les enjeux réels du travail. Plutôt que d'opposer diplôme et expérience, je préconise de combiner les deux : suivre une formation tout en accumulant des expériences concrètes. Cette complémentarité renforce l'employabilité et prépare les jeunes à relever les défis professionnels."],
        ],
    ],
    [
        'combo' => 19,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Envoyez un message à vos amis pour les inviter à passer un week-end chez vous et à pratiquer ensemble des activités sportives.', 'correction' => "Salut les amis !\n\nJe vous propose de passer un week-end sportif ensemble chez moi. On pourrait faire du vélo, de la randonnée ou même une petite session de fitness dans le jardin. Ce serait l'occasion de profiter du plein air, de se dépenser et de passer un bon moment ensemble. J'ai prévu aussi des repas simples et des collations pour nous recharger après l'effort.\n\nDites-moi si vous êtes partants et quelles activités vous tenteraient le plus. J'ai vraiment hâte qu'on passe ce week-end actif et amusant tous ensemble !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Écrivez un article sur votre blog pour raconter pourquoi vous avez décidé de changer votre alimentation (vos habitudes alimentaires).', 'correction' => "Raisons Qui M'ont Poussé à Changer Mes Habitudes Alimentaires\n\nChanger ses habitudes alimentaires peut sembler difficile, mais c'est un voyage gratifiant. Adopter une alimentation saine améliore votre qualité de vie globale.\n\nDepuis quelques mois, j'ai décidé de modifier ma façon de manger. J'ai réalisé que je me sentais constamment fatigué et sans énergie. J'ai compris que mon régime alimentaire riche en sucres et en aliments transformés en était la cause. J'ai donc opté pour une alimentation plus équilibrée, riche en légumes, fruits, protéines maigres, et grains entiers.\n\nLes résultats ont été rapides : plus d'énergie, meilleure digestion, et une peau plus éclatante.\n\nJe vous encourage à réfléchir à vos propres habitudes alimentaires et à envisager un changement vers une alimentation plus saine. Vous vous sentirez mieux et plus énergique !"],
            ['task' => 3, 'prompt' => 'La sieste au travail.', 'documents' => [['title' => 'Document 1', 'content' => 'Faire une sieste au travail présente de nombreux bénéfices pour les salariés et les entreprises. Permettre aux employés de se reposer quelques minutes peut accroître leur productivité et améliorer leur santé et leur bien-être. Les courtes siestes renforcent la concentration, diminuent le stress et améliorent l\'humeur. Elles peuvent aussi réduire les coûts liés à la fatigue et aux accidents. Les entreprises devraient donc envisager d\'intégrer cette pratique pour leur personnel.'], ['title' => 'Document 2', 'content' => 'Même si la sieste au travail présente de nombreux bénéfices, il n\'est pas facile pour toutes les entreprises d\'aménager des espaces ou des lits pour cela. Les contraintes financières, logistiques ou les règles strictes peuvent empêcher les salariés de se reposer. De plus, certains employés peuvent se sentir mal à l\'aise. Il est donc important que les entreprises évaluent avantages et limites et trouvent des solutions pour favoriser le repos.']], 'correction' => "La sieste au travail : un atout pour productivité et bien-être\n\nLa sieste au travail suscite un débat entre avantages et limites. Le Document 1 met en avant ses effets positifs : meilleure concentration, vigilance et bien-être des employés. À l'inverse, le Document 2 souligne les contraintes pratiques et psychologiques, comme l'absence de salles adaptées ou la gêne ressentie par certains salariés.\n\nÀ mon avis, la sieste au travail présente de nombreux bénéfices lorsqu'elle est bien organisée. Elle permet de récupérer de l'énergie, d'améliorer la concentration et le moral, et même de réduire les coûts liés à la fatigue. Cependant, il faut tenir compte des contraintes logistiques et de l'acceptation des employés. Les entreprises pourraient proposer des solutions créatives comme des salles de repos modulables ou des horaires flexibles pour favoriser cette pratique sans perturber le fonctionnement quotidien. Une approche équilibrée permettrait d'allier performance professionnelle et bien-être des salariés."],
        ],
    ],
];
