<?php
declare(strict_types=1);

/** @return list<array{combo:int,tasks:list<array{task:int,prompt:string,correction:string,documents?:list<array{title?:string,content:string}>}>}> */
return [
    [
        'combo' => 1,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous partez en vacances avec vos amis, vous avez trouvé un hôtel. Vous écrivez un message à vos amis pour décrire cet hôtel (localisation, prix, équipements, etc.) et vous leur proposez de réserver cet hôtel.', 'correction' => "Salut les amis,\n\nJ'ai enfin trouvé un hôtel parfait pour nos vacances ! Il s'appelle L'Oasis Bleu et il se trouve à seulement 5 minutes de la plage. L'endroit est magnifique : les chambres sont spacieuses, climatisées et possèdent un balcon avec vue sur la mer. Il y a aussi une piscine extérieure, un restaurant buffet, une salle de sport et même un spa.\n\nLe prix est de 80 € par nuit et par chambre, petit-déjeuner compris, ce qui est très raisonnable pour la qualité du service. Le Wi-Fi est gratuit et le personnel parle plusieurs langues.\n\nJe pense qu'on devrait réserver rapidement avant que les places ne partent. Qu'en pensez-vous ?\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous êtes parti(e) travailler à l\'étranger. Vous envoyez un message à vos amis pour raconter cette nouvelle expérience professionnelle. Vous expliquez ce que vous avez le plus aimé.', 'correction' => "Ma nouvelle vie à l'étranger\n\nSalut les amis,\n\nJe voulais vous donner des nouvelles de ma nouvelle aventure professionnelle à l'étranger ! Depuis trois mois, je travaille dans une entreprise internationale à Montréal, et c'est une expérience incroyable. J'ai découvert une façon de travailler beaucoup plus ouverte et collaborative. Les collègues sont très accueillants et toujours prêts à aider.\n\nCe que j'ai le plus aimé jusqu'à présent, c'est la diversité culturelle : chaque jour, je parle avec des personnes venant du monde entier. Cela m'a permis d'améliorer mon français et mon anglais tout en découvrant d'autres modes de vie.\n\nJ'aime aussi l'équilibre entre vie professionnelle et vie personnelle ici : on travaille sérieusement, mais on respecte le temps libre. Cette expérience m'a beaucoup appris sur moi-même et m'a donné confiance pour l'avenir.\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 3, 'prompt' => 'Les jeux vidéo : Pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Des études ont montré que certaines zones du cerveau de l\'adulte peuvent être développées en jouant aux jeux vidéo. Ainsi, il peut être intéressant de jouer aux jeux vidéo, car ils permettent, par exemple, d\'améliorer la capacité d\'analyse, la capacité à faire des choix et la rapidité de réaction. C\'est une bonne nouvelle, car la répartition des joueurs par âge montre que 83 % des joueurs sont des adultes. Cependant, il convient de rester prudent, car certains jeux vidéo ne favorisent pas ce type d\'amélioration sur le cerveau.'],
                ['title' => 'Document 2', 'content' => 'Pendant trois ans, des enfants âgés de 8 à 17 ans ont participé à une étude sur les jeux vidéo. Les résultats de cette étude montrent que les enfants qui jouent beaucoup aux jeux vidéo sont plus violents, plus nerveux et plus stressés que ceux qui ne jouent pas ou peu. Ceux qui jouent beaucoup ont également moins de bons résultats à l\'école. Il est donc conseillé aux parents d\'être vigilants et de limiter l\'usage de ces jeux par leurs enfants.'],
            ], 'correction' => "Les jeux vidéo dans notre société\n\nLes jeux vidéo provoquent des débats partagés. Le premier document explique qu'ils peuvent stimuler certaines zones du cerveau chez les adultes, en améliorant la mémoire, la concentration et la rapidité de réaction. Le second souligne, au contraire, les effets négatifs chez les enfants : stress, agressivité, baisse des résultats scolaires et dépendance.\n\nPour ma part, je pense que les jeux vidéo peuvent avoir un impact positif s'ils sont utilisés de manière modérée et encadrée. Certains jeux développent la réflexion, la stratégie, la coopération et même la créativité. Ils peuvent aussi être un bon moyen de détente ou de socialisation. Cependant, il est essentiel de fixer des limites, surtout pour les enfants, car un excès de jeu peut nuire à la santé mentale et physique. Passer trop d'heures devant un écran favorise la fatigue, l'isolement et la perte de concentration. Les parents doivent donc surveiller le contenu et la durée des sessions de jeu. Enfin, les concepteurs devraient proposer davantage de jeux éducatifs et responsables, afin de faire du jeu vidéo un véritable outil d'apprentissage et de plaisir équilibré."],
        ],
    ],
    [
        'combo' => 2,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Salut ! Je sais que tu fais du sport depuis le mois dernier. Ça m\'intéresse beaucoup et j\'aimerais bien venir avec toi. Tu peux m\'en dire plus ? À bientôt ! Camille — Vous répondez à votre ami Camille. Dans votre message, vous décrivez votre activité sportive et vous donnez des informations utiles (lieu, durée, prix, etc.).', 'correction' => "Salut Camille,\n\nJe suis super content que tu t'intéresses à mon activité sportive ! Depuis le mois dernier, je fais du fitness en groupe dans une salle qui s'appelle Move Center, située près du centre commercial. Les séances durent 1 heure, trois fois par semaine : le lundi, le mercredi et le vendredi à 18 h 30.\n\nLes cours sont animés par un coach très motivant, et on alterne entre cardio, musculation légère et étirements. C'est parfait pour améliorer l'endurance et garder la forme sans se blesser. L'ambiance est vraiment sympa, tout le monde s'encourage !\n\nL'abonnement coûte 35 € par mois, et la première séance d'essai est gratuite. Si tu veux, tu peux venir avec moi la semaine prochaine !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Tout quitter pour changer de vie ? Il y a deux ans, nous avons décidé de changer de vie. Paul a quitté son poste de banquier à Paris et nous avons ouvert une boulangerie à Calgary ! Que pensez-vous de cette décision ? Avez-vous déjà vécu un grand changement, professionnel ou personnel ? Paul et Naïma — Vous avez lu ce message sur un forum internet. Vous répondez à Paul et Naïma. Dans votre message, vous donnez votre opinion sur le choix de Paul et de Naïma et vous racontez comment vous feriez si vous étiez à leur place.', 'correction' => "Tout quitter pour changer de vie ?\n\nBonjour Paul et Naïma,\n\nJ'ai beaucoup aimé lire votre message, et je trouve votre décision très courageuse et inspirante. Quitter une vie stable à Paris pour ouvrir une boulangerie à Calgary, c'est un vrai pari, mais aussi une belle preuve de passion et de liberté. Je pense que changer de vie permet de se redécouvrir et de donner un nouveau sens à son quotidien.\n\nSi j'étais à votre place, j'aurais sûrement peur au début, mais je crois que le bonheur se trouve souvent dans le risque. Moi aussi, j'aimerais un jour quitter mon travail de bureau pour créer mon propre projet, peut-être un café ou une petite librairie.\n\nBravo pour votre choix ! Vous avez osé suivre votre cœur, et c'est souvent la clé du succès et du bonheur.\n\nBien à vous,\nelite tcf canada"],
            ['task' => 3, 'prompt' => 'Le bien-être au travail', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Nous avons installé, dans votre entreprise, des bureaux réglables qui montent et descendent, ceci pour permettre aux employés de choisir la position qui leur convient le mieux pour travailler. Les employés sont satisfaits et disent qu\'ils sont plus productifs et plus efficaces lors des négociations au téléphone par exemple. Même le climat social est plus convivial et la communication verbale entre collègues s\'est renforcée. « Lorie, responsable ».'],
                ['title' => 'Document 2', 'content' => 'De nos jours, les entreprises veulent toujours plus de productivité et d\'efficacité, et les employés passent plus de temps sur les lieux de travail. Les entreprises cherchent toujours des moyens ou astuces pour convaincre leurs employés de travailler plus et qu\'elles pensent à leur santé. Moi, ce qui m\'importe, c\'est de faire mon job sur mon temps de travail réel sans être obligé de faire des rallonges en heures supplémentaires. « Florian, ingénieur ».'],
            ], 'correction' => "Débat autour de bien-être au travail\n\nDe nos jours, la question du bien-être au travail occupe une place importante dans les entreprises. Le premier texte explique comment certaines sociétés améliorent les conditions de travail en installant du matériel ergonomique, ce qui renforce la satisfaction, la productivité et la communication entre collègues. Le second, au contraire, dénonce la recherche excessive de performance, souvent au détriment de la santé et du temps personnel des employés.\n\nÀ mon avis, le bien-être au travail doit être une priorité pour toutes les entreprises. Un salarié heureux et écouté travaille mieux et reste plus longtemps dans son poste. Les dirigeants devraient favoriser un équilibre entre la vie professionnelle et la vie personnelle, en proposant par exemple des horaires flexibles ou des espaces de détente. Le confort matériel, comme des bureaux adaptés, est important, mais l'aspect humain l'est encore plus : il faut encourager le dialogue, la reconnaissance et la confiance. De plus, le bien-être au travail ne se limite pas à l'absence de stress ; il implique aussi la motivation et le sentiment d'appartenance à une équipe. Un bon climat professionnel profite à la fois aux employés et aux entreprises."],
        ],
    ],
    [
        'combo' => 3,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Je suis votre amie Anna et je compte passer un week-end dans ta ville. Donnez-moi des informations sur les moyens de transport pour explorer la ville. Répondez à Anna dans un message.', 'correction' => "Salut Anna,\n\nJe suis ravie que tu viennes passer le week-end ici ! Pour te déplacer, c'est très simple. Le tramway est le moyen le plus pratique : il traverse toute la ville et dessert les principaux sites touristiques. Il y a aussi plusieurs bus qui circulent jusqu'à minuit.\n\nSi tu préfères un moyen plus libre, tu peux utiliser les vélos en libre-service, parfaits pour visiter le centre-ville. Les taxis et applications de transport sont aussi disponibles et abordables. Je te conseille d'acheter un pass journée à 6 €, valable sur tous les transports.\n\nJ'ai hâte de te revoir !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez assisté à une fête de voisins du quartier, écrivez un blog pour montrer pourquoi vous avez aimé cette fête.', 'correction' => "Une fête de voisins inoubliable\n\nChers lecteurs,\n\nLe week-end dernier, notre quartier a organisé une fête des voisins, et c'était une expérience formidable ! Tout le monde avait apporté quelque chose à manger : des salades, des gâteaux, des spécialités de différents pays. Cette diversité rendait la table aussi colorée que conviviale.\n\nJ'ai beaucoup aimé l'ambiance chaleureuse et la bonne humeur générale. Les enfants jouaient ensemble pendant que les adultes discutaient et faisaient connaissance. C'était l'occasion parfaite de rencontrer de nouvelles personnes, d'échanger avec des voisins qu'on croise souvent sans vraiment leur parler.\n\nIl y avait aussi de la musique, quelques jeux et un petit concours de desserts. Ce moment simple, sans prétention, m'a rappelé l'importance de la solidarité et du vivre ensemble. Grâce à cette fête, notre quartier semble plus uni, et j'espère que cette belle tradition se répétera chaque année."],
            ['task' => 3, 'prompt' => 'Les distributeurs de boissons dans les lycées : Pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Je suis en faveur des distributeurs de boissons dans les lycées. Premièrement, ils offrent une commodité supplémentaire pour les élèves, notamment pour ceux qui n\'ont pas le temps de passer à la cafétéria pendant les pauses. Deuxièmement, s\'ils sont bien gérés, ces distributeurs peuvent offrir une gamme de boissons saines, comme de l\'eau, du jus de fruits pur et des boissons aux fruits sans sucre ajouté. Ces distributeurs peuvent être une source de revenus supplémentaire pour l\'école, qui peut être réinvestie dans l\'amélioration des infrastructures ou des programmes scolaires.'],
                ['title' => 'Document 2', 'content' => 'Je suis contre l\'installation de distributeurs de boissons dans les lycées. Ma principale préoccupation est liée à la santé des élèves. Malheureusement, beaucoup de ces distributeurs sont remplis de boissons sucrées et de sodas qui contribuent à l\'obésité infantile et à d\'autres problèmes de santé comme le diabète. Même les jus de fruits, qui peuvent sembler sains, contiennent souvent beaucoup de sucre. Les écoles devraient être des lieux qui encouragent des habitudes alimentaires saines et je crains que la présence de ces distributeurs n\'encourage une consommation excessive de boissons sucrées.'],
            ], 'correction' => "Les distributeurs de boissons à l'école\n\nLes distributeurs de boissons dans les lycées font débat. Le premier document met en avant leurs avantages : ils offrent un service pratique aux élèves, surtout à ceux qui n'ont pas le temps d'aller à la cafétéria. Bien gérés, ils peuvent proposer des boissons saines et générer des revenus pour les établissements. En revanche, le second texte dénonce leurs effets négatifs sur la santé, notamment la consommation excessive de sucre et les risques d'obésité chez les jeunes.\n\nÀ mon avis, les distributeurs dans les lycées peuvent être une bonne idée, mais uniquement s'ils sont réglementés. Ils devraient proposer de l'eau, des jus naturels et des boissons sans sucre ajouté. Les établissements scolaires ont un rôle éducatif : ils doivent encourager une alimentation équilibrée et sensibiliser les élèves aux dangers du sucre. De plus, il serait utile d'afficher des informations nutritionnelles sur chaque produit. Cela permettrait de responsabiliser les jeunes tout en leur laissant le choix. Si ces conditions ne sont pas respectées, mieux vaudrait supprimer ces distributeurs pour préserver la santé des élèves."],
        ],
    ],
    [
        'combo' => 4,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous voulez passer un week-end avec vos amis et faire du sport. Vous leur écrivez une lettre pour proposer ça en citant (date, lieu, programme).', 'correction' => "Salut les amis,\n\nJ'espère que vous allez bien ! J'aimerais vous proposer de passer un week-end sportif tous ensemble. Ce serait l'occasion de se retrouver, de s'amuser et de bouger un peu. Je pensais au samedi 23 et dimanche 24 mars, dans le parc naturel des Montagnes Vertes, à environ une heure de la ville.\n\nNous pourrions partir tôt samedi matin pour faire une grande randonnée et profiter de la nature. À midi, on partagerait un pique-nique en plein air avant de continuer avec des activités sportives comme le vélo, le foot ou l'escalade selon les envies. Le soir, on organiserait un barbecue et on dormirait sous tente. Le dimanche, on prendrait un bon petit-déjeuner, puis on ferait une séance de détente avant de rentrer en fin de journée.\n\nJ'espère que vous êtes partants ! Dites-moi vite si vous venez pour que je réserve le camping.\n\nÀ très bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Écrivez un article sur votre blog pour raconter pourquoi vous avez décidé de changer votre alimentation (vos habitudes alimentaires).', 'correction' => "Pourquoi j'ai décidé de changer mon alimentation\n\nDepuis quelques mois, j'ai pris conscience que mes habitudes alimentaires n'étaient pas très saines. Je mangeais souvent à la hâte, sans vraiment faire attention à la qualité de ce que je consommais. Résultat : fatigue, manque d'énergie et quelques kilos en trop. C'est à ce moment-là que j'ai décidé de changer mon alimentation et d'adopter un mode de vie plus équilibré.\n\nJ'ai commencé par réduire les aliments industriels, le sucre et les boissons gazeuses. À la place, j'ai intégré davantage de fruits, légumes frais, légumineuses et céréales complètes. J'ai aussi pris l'habitude de cuisiner moi-même, ce qui m'a permis de redécouvrir le plaisir de préparer de bons plats maison.\n\nEn quelques semaines, j'ai remarqué une vraie différence : je me sens plus léger, plus concentré et en meilleure forme. Ce changement ne concerne pas seulement ce que je mange, mais aussi ma façon de vivre : manger sainement, c'est prendre soin de soi chaque jour."],
            ['task' => 3, 'prompt' => 'La sieste au travail : Pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'D\'après le site « siestepourtous.com », une micro-sieste permettrait d\'augmenter la productivité et la créativité des travailleurs de 35 %, ce qui est un avantage considérable pour l\'employé et l\'employeur. Aussi, la sieste au travail permettrait d\'augmenter la mémoire et donc la concentration. Un salarié reposé ne penserait plus à dormir et serait davantage disponible pour ses missions. Grâce à la sieste au bureau, le stress et les risques cardiaques diminueraient.'],
                ['title' => 'Document 2', 'content' => 'Bien que les effets positifs d\'une power nap aient été scientifiquement prouvés, il existe encore des personnes qui s\'y opposent et y voient des inconvénients. La sieste au travail est assez difficile en termes de faisabilité. En effet, ce n\'est pas dans les moyens de toutes les entreprises de mettre en place des lits et des salles dédiées à cette pratique. Lorsqu\'une entreprise veut mettre en place un temps de repos dans son organisation, elle n\'est pas tout à fait libre de faire selon son bon vouloir. L\'entreprise devra se conformer à certaines règles : la mise à disposition d\'un local dédié et de matériel, l\'égalité de traitement entre salariés, l\'établissement d\'une charte, etc.'],
            ], 'correction' => "À mon avis, la sieste au travail peut être très bénéfique si elle est bien encadrée. Dans un monde professionnel souvent stressant, une courte pause permet de récupérer et d'améliorer la concentration. Cependant, il est vrai que sa mise en place doit être adaptée à chaque entreprise. Toutes ne disposent pas d'un espace ou d'un budget suffisant. Pour moi, il faudrait commencer par sensibiliser les employeurs aux avantages de la sieste et proposer des solutions simples, comme des fauteuils de repos ou des zones calmes. Une bonne gestion du temps de pause peut ainsi renforcer la motivation, la santé et l'efficacité des employés."],
        ],
    ],
    [
        'combo' => 5,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Rédigez un message pour inviter votre ami(e) à passer ses vacances dans votre ville en précisant les lieux et les endroits à visiter.', 'correction' => "Salut Karim,\n\nJ'espère que tu vas bien ! Je voulais t'inviter à venir passer tes prochaines vacances dans ma ville, car il y a plein de choses à découvrir ici. C'est une destination idéale pour se détendre et profiter d'un séjour entre nature, culture et gastronomie.\n\nTu pourrais visiter la vieille médina, avec ses ruelles animées, ses artisans et ses cafés traditionnels. Le musée de la ville vaut aussi le détour : il retrace toute l'histoire locale avec de magnifiques expositions. Si tu aimes la nature, le parc national voisin est parfait pour faire des balades ou un pique-nique au bord du lac. Et bien sûr, ne manque pas le marché central, où tu pourras goûter les spécialités locales et acheter quelques souvenirs.\n\nJe suis sûr que tu vas adorer ! Dis-moi quand tu serais disponible, et je m'occuperai de tout organiser.\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez participé à un concours pour gagner un séjour de deux semaines dans votre ville préférée. Le thème de ce concours est « Mon artiste préféré ». Écrivez un article de blog pour parler de votre artiste préféré.', 'correction' => "Depuis plusieurs années, je suis fasciné par Stromae, un artiste belge qui a révolutionné la chanson francophone. Ce que j'aime chez lui, c'est sa capacité à mélanger les styles : pop, électro, rap, et même des sonorités africaines. Ses chansons ne sont pas seulement entraînantes, elles font réfléchir.\n\nÀ travers ses textes, Stromae parle de la vie quotidienne, de la solitude, de l'amour, et même de la maladie mentale. Par exemple, dans Formidable ou L'enfer, il exprime des émotions profondes que beaucoup de jeunes ressentent aujourd'hui. Ses paroles sont simples mais puissantes, et elles touchent directement le cœur.\n\nEn plus de sa musique, Stromae est un artiste complet, qui soigne chaque détail : ses clips, ses vêtements, sa mise en scène… Tout est original et plein de sens. C'est pour toutes ces raisons que Stromae est, pour moi, bien plus qu'un chanteur : c'est un véritable créateur d'émotions."],
            ['task' => 3, 'prompt' => 'La chasse aux animaux : pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => '« Je suis de ceux qui n\'arrivent pas à comprendre comment l\'on peut prendre du plaisir à tuer des animaux. Je suis de ceux qui n\'arrivent pas à comprendre comment on peut prétendre aimer la nature alors qu\'on la détruit. » Gala, 29 ans'],
                ['title' => 'Document 2', 'content' => '« Les gens chassent pour différentes raisons : la subsistance, le commerce, la conservation et l\'aménagement de la faune, la protection de la propriété, l\'exercice, le loisir et le prestige. » David, journaliste de la FRM'],
            ], 'correction' => "Les deux documents présentent deux points de vue opposés sur la chasse aux animaux. Dans le premier document, l'auteure exprime une position ferme contre cette pratique, qu'elle considère comme une forme de cruauté incompatible avec l'amour de la nature. En revanche, le deuxième document explique que la chasse peut avoir plusieurs motivations : la subsistance, le commerce, la régulation de la faune, ou encore le loisir et le prestige.\n\nÀ mon avis, la chasse ne devrait être autorisée que dans des conditions strictement encadrées. Si elle est pratiquée pour réguler certaines espèces et préserver l'équilibre écologique, elle peut avoir une utilité réelle. Cependant, la chasse pour le plaisir ou le prestige me semble inacceptable, car elle conduit à la souffrance animale et à la destruction de la biodiversité. De nos jours, il existe d'autres activités de plein air permettant d'entretenir un lien avec la nature sans la mettre en danger. Il serait préférable de sensibiliser le public à la protection des animaux et de promouvoir une cohabitation harmonieuse entre l'humain et la faune."],
        ],
    ],
    [
        'combo' => 6,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous souhaitez assister à un festival de cinéma dans votre ville. Vous écrivez un message à votre ami(e) pour lui proposer de venir avec vous. Vous lui donnez toutes les informations nécessaires sur l\'événement (films, dates et horaires, tarifs, etc.).', 'correction' => "Salut Nadia,\n\nJ'espère que tu vas bien ! Je voulais te proposer de venir avec moi au Festival du Cinéma de notre ville, qui aura lieu du 14 au 18 novembre au Centre Culturel Lumière. Pendant ces cinq jours, on pourra découvrir des films français et internationaux, assister à des avant-premières et rencontrer plusieurs réalisateurs.\n\nLe programme est vraiment varié : films d'auteur, documentaires, courts métrages et animations. Les projections commenceront chaque jour à 15 h et se termineront vers 22 h. Il y aura aussi un débat public le samedi soir sur le thème du cinéma et de la société.\n\nLe pass pour toute la durée du festival coûte 25 €, et un billet à la séance est à 6 €. Je pensais y aller vendredi soir ou samedi après-midi, si tu es disponible.\n\nQu'en dis-tu ? Ce serait super d'y aller ensemble !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez accueilli un(e) étudiant(e) étranger(e) pendant une semaine chez vous. Sur votre blog, vous écrivez un article pour raconter cette semaine. Vous expliquez pourquoi vous avez aimé cette expérience.', 'correction' => "Une belle semaine d'échanges culturels\n\nLa semaine dernière, j'ai eu le plaisir d'accueillir Sofia, une étudiante espagnole venue suivre un programme d'échange universitaire. Dès son arrivée, nous avons tout de suite sympathisé. Elle était curieuse de découvrir notre culture et notre mode de vie, et j'étais ravi d'en apprendre davantage sur l'Espagne.\n\nPendant la semaine, nous avons visité plusieurs lieux emblématiques de la ville : le musée d'art moderne, le vieux quartier et le marché local. Nous avons aussi cuisiné ensemble des plats traditionnels de nos deux pays : elle m'a appris à préparer une délicieuse tortilla, et je lui ai fait goûter un couscous maison.\n\nCe que j'ai le plus aimé dans cette expérience, c'est l'échange humain et culturel. Vivre avec quelqu'un d'une autre nationalité permet d'ouvrir son esprit, de mieux comprendre les différences et de créer de vrais liens d'amitié. C'était une expérience enrichissante que je recommencerais sans hésiter."],
            ['task' => 3, 'prompt' => 'La Restauration Rapide.', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Les restaurants rapides se distinguent par leur engagement à proposer une variété de plats équilibrés, respectant strictement les normes d\'hygiène. En laissant aux clients la liberté de composer leur propre menu, ces établissements les responsabilisent dans leurs choix alimentaires, tout en satisfaisant leurs préférences gustatives.'],
                ['title' => 'Document 2', 'content' => 'Les spécialistes affirment que manger régulièrement dans des restaurants de fast-food, qui proposent de la restauration rapide, est dangereux pour la santé. La nourriture servie est souvent la même : frites, hamburgers et boissons sucrées. Ces aliments contiennent une grande quantité de calories, bien trop pour un seul repas. De plus, la plupart des produits dans ces restaurants sont emballés dans du plastique. Par conséquent, manger dans un fast-food augmente la production de déchets plastiques, ce qui est nuisible pour l\'environnement.'],
            ], 'correction' => "Les deux documents présentent des points de vue opposés sur la restauration rapide. Dans le premier document, l'auteure critique fortement ce type de restauration qu'elle juge mauvaise pour la santé et de qualité médiocre. En revanche, le deuxième document défend la restauration rapide, considérant qu'elle peut être équilibrée si le client fait des choix raisonnables et responsables.\n\nÀ mon avis, la restauration rapide n'est pas forcément mauvaise si elle est consommée avec modération. Ces établissements offrent une solution pratique pour les personnes pressées, notamment dans les grandes villes où le rythme de vie est intense. De plus, certains restaurants proposent aujourd'hui des options plus saines, comme des salades ou des fruits. Cependant, il est important de ne pas en faire une habitude quotidienne. Manger trop souvent dans ce type de restaurant peut nuire à la santé à cause de la forte teneur en graisses, en sel et en sucre des plats. Je pense donc qu'il faut apprendre à mieux choisir ses repas et privilégier une alimentation variée. La clé réside dans l'équilibre entre plaisir, rapidité et bien-être."],
        ],
    ],
    [
        'combo' => 7,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Parc de loisirs : « J\'ai hâte de passer la journée avec toi demain. S\'il te plaît, dis-moi, quelle activité nous pourrons faire ? » — Répondez à votre ami(e) pour lui décrire la sortie (horaires, transport, activités, etc.).', 'correction' => "Salut !\n\nJ'ai trop hâte aussi de passer cette journée avec toi demain ! Voici le programme que j'ai prévu pour notre sortie au parc de loisirs Aventure & Nature.\n\nOn se retrouvera à 9 h 30 devant la gare centrale, puis on prendra le bus 42, qui nous déposera directement à l'entrée du parc vers 10 h 15. Le billet d'entrée coûte 20 €, et il donne accès à toutes les activités.\n\nSur place, on pourra commencer par un parcours d'accrobranche pour bien se dépenser, puis on ira faire du karting et du mini-golf. Vers 13 h, on déjeunera au restaurant du parc — ils proposent un menu simple et pas trop cher. L'après-midi, on pourra se détendre au lac artificiel, faire du pédalo ou simplement profiter du soleil.\n\nOn repartira vers 18 h pour être de retour en ville vers 19 h.\nPrépare des vêtements confortables et ton appareil photo !\n\nÀ demain !\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Écrivez un message à vos amis pour leur raconter votre expérience lors d\'un salon du livre (conférence, expositions et rencontre avec les auteurs…).', 'correction' => "Salut les amis,\n\nJe voulais vous raconter ma super expérience au Salon du Livre qui s'est tenu ce week-end au centre des expositions de la ville. C'était vraiment passionnant ! J'y ai passé toute la journée à découvrir de nouveaux auteurs, à feuilleter des livres venus du monde entier et à assister à plusieurs conférences très enrichissantes sur la littérature contemporaine.\n\nJ'ai eu la chance de rencontrer deux écrivains que j'admire beaucoup : Claire Martin, qui a parlé de son dernier roman, et Karim Benali, qui a gentiment pris le temps de discuter avec le public et de signer des dédicaces. Il y avait aussi une exposition de bandes dessinées et un espace pour les jeunes auteurs.\n\nL'ambiance était conviviale, pleine de découvertes et d'échanges. Si vous aimez lire, je vous conseille vraiment d'y aller l'an prochain, c'est une expérience à ne pas manquer !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 3, 'prompt' => 'Faire ses courses alimentaires chez les producteurs locaux ou au supermarché', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Jean qui vit à la campagne favorise l\'achat des produits alimentaires directement à la ferme pour la bonne qualité, quitte à payer un peu plus cher.'],
                ['title' => 'Document 2', 'content' => 'Camille qui vit dans la ville préfère faire ses courses au supermarché pour la variété qu\'il propose et pour les prix abordables.'],
            ], 'correction' => "Les deux documents présentent deux points de vue différents sur la façon de faire ses courses. Dans le premier document, Jean, qui habite à la campagne, préfère acheter ses produits directement à la ferme. Il met en avant la qualité des aliments, même si cela coûte un peu plus cher. En revanche, dans le deuxième document, Camille, citadine, choisit le supermarché pour la variété des produits proposés et les prix plus bas.\n\nÀ mon avis, acheter directement chez les producteurs locaux est une excellente façon de soutenir l'économie locale et de consommer des produits plus sains et plus frais. Les aliments y sont souvent de meilleure qualité et respectent davantage l'environnement. Cependant, tout le monde n'a pas la possibilité de le faire, surtout en ville où les marchés fermiers sont parfois rares. Les supermarchés restent donc une option pratique grâce à leurs horaires étendus et leurs prix accessibles. Idéalement, il faudrait combiner les deux approches : privilégier les produits locaux quand c'est possible, tout en profitant de la praticité du supermarché pour le reste. Cela permettrait d'allier qualité, économie et responsabilité."],
        ],
    ],
    [
        'combo' => 8,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous souhaitez assister à un festival de cinéma dans votre ville. Vous écrivez un message à votre ami(e) pour lui proposer de venir avec vous. Vous lui donnez toutes les informations nécessaires sur l\'événement (films, dates et horaires, tarifs, etc.).', 'correction' => "Salut Sarah,\n\nJ'espère que tu vas bien ! Je voulais te proposer de venir avec moi au Festival du Cinéma de notre ville, qui aura lieu du 12 au 16 novembre au Théâtre Lumière. Pendant cinq jours, plusieurs films français et internationaux seront projetés, dont certains en avant-première.\n\nLe programme est très varié : comédies, documentaires, courts métrages et films d'animation. Il y aura aussi des rencontres avec des réalisateurs et un atelier d'initiation au cinéma le samedi après-midi. Les projections commencent chaque jour à 14 h et se terminent vers 22 h.\n\nLe pass pour toute la semaine coûte 30 €, mais on peut aussi acheter un billet à 7 € par séance. J'ai déjà réservé ma place pour le vendredi soir, où un film marocain sera présenté.\n\nÇa te dirait de venir avec moi ? Ce serait super sympa d'y aller ensemble !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez récemment assisté à un festival de cinéma et vous avez vu un film qui vous a particulièrement marqué. Écrivez un message à vos amis pour leur raconter votre expérience lors de ce festival et leur parler de votre film préféré.', 'correction' => "Salut les amis,\n\nJe voulais vous parler de mon expérience au Festival du Cinéma de notre ville, qui a eu lieu la semaine dernière. C'était vraiment un moment exceptionnel ! J'ai eu la chance d'assister à plusieurs projections, mais le film qui m'a le plus marqué s'intitule « Le Chemin du Silence ».\n\nCe film raconte l'histoire d'un jeune homme sourd passionné de musique. Malgré son handicap, il tente de réaliser son rêve de devenir compositeur. L'histoire est très émouvante, les acteurs jouent avec une justesse incroyable, et la bande sonore est magnifique. J'ai été particulièrement touché par la façon dont le réalisateur montre la force du courage et la beauté du silence.\n\nL'ambiance du festival était aussi formidable : des échanges avec les réalisateurs, une salle pleine d'émotions et un public très attentif. Si vous aimez les films humains et inspirants, je vous le recommande absolument !\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 3, 'prompt' => 'Les maisons de retraite, pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Les maisons de retraite sont une bonne solution pour les personnes âgées. Elles y reçoivent des soins adaptés et sont entourées de professionnels. De plus, elles peuvent participer à des activités qui les aident à rester socialement actives, ce qui évite l\'isolement. Dans certains cas, c\'est mieux que de rester seules à la maison.'],
                ['title' => 'Document 2', 'content' => 'Les maisons de retraite peuvent éloigner les personnes âgées de leur famille et créer un sentiment d\'abandon. De plus, les conditions de vie ne sont pas toujours idéales et il arrive que certains établissements manquent de personnel qualifié. Je crois que le soutien à domicile est une meilleure option pour vieillir en famille.'],
            ], 'correction' => "Les deux documents présentent des points de vue opposés sur les maisons de retraite. Dans le premier document, elles sont décrites comme une bonne solution pour les personnes âgées, car elles y reçoivent des soins adaptés et peuvent participer à des activités sociales qui évitent l'isolement. En revanche, le deuxième document met en avant leurs inconvénients : certaines personnes âgées s'y sentent abandonnées et les conditions de vie ne sont pas toujours satisfaisantes, notamment à cause du manque de personnel qualifié.\n\nÀ mon avis, le choix d'une maison de retraite dépend de la situation de chaque personne. Pour les personnes âgées malades ou isolées, ces établissements peuvent représenter une véritable aide grâce aux soins et à la présence de professionnels. Cependant, pour celles qui sont encore autonomes, le maintien à domicile est préférable. Cela leur permet de rester proches de leur famille et de conserver leurs habitudes quotidiennes. Le plus important est de garantir un accompagnement humain et chaleureux, quel que soit le lieu de vie. Les maisons de retraite devraient devenir des espaces de vie agréables, où le bien-être et la dignité des résidents sont réellement respectés."],
        ],
    ],
    [
        'combo' => 9,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Salut ! Je suis d\'accord pour m\'occuper de ta maison et de ton jardin pendant tes vacances. Tu peux m\'expliquer ce que je dois faire ? À bientôt, Cédric — Vous répondez à Cédric. Dans votre message, vous décrivez ce qu\'il doit faire chez vous pendant votre absence.', 'correction' => "Salut Cédric,\n\nMerci beaucoup d'avoir accepté de t'occuper de ma maison pendant mes vacances ! Voici ce qu'il faudra faire :\n\nD'abord, arroser les plantes du salon et du jardin tous les deux jours. Il suffit d'utiliser l'arrosoir vert qui se trouve près de la porte d'entrée. Pense aussi à ouvrir un peu les fenêtres le matin pour aérer la maison.\n\nEnsuite, il faudra sortir les poubelles le mercredi soir, car le ramassage se fait le jeudi matin. Les sacs noirs sont pour les ordures ménagères, et les sacs jaunes pour le recyclage.\n\nEnfin, si tu peux, vérifie la boîte aux lettres deux ou trois fois par semaine et pose le courrier sur la table du salon.\n\nEncore merci pour ton aide ! Je te laisserai les clés et quelques provisions avant mon départ.\n\nÀ bientôt,\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Vous avez fait un séjour à l\'étranger organisé par une agence de voyage. Vous êtes déçu(e) par les services proposés. Vous écrivez à l\'agence pour raconter votre expérience et donner votre opinion sur ce séjour.', 'correction' => "Objet : Réclamation concernant mon séjour à l'étranger\n\nMadame, Monsieur,\n\nJe me permets de vous écrire afin de vous faire part de ma déception à la suite du séjour organisé par votre agence du 10 au 17 octobre à Lisbonne. Malheureusement, plusieurs éléments n'étaient pas conformes à ce qui avait été annoncé dans votre brochure.\n\nTout d'abord, l'hôtel prévu n'était pas celui mentionné lors de la réservation. La chambre était petite, bruyante et la propreté laissait à désirer. De plus, le programme des excursions a été modifié sans explication : certaines visites ont été annulées, et aucun guide francophone n'était disponible, contrairement à ce qui avait été promis.\n\nJ'avais choisi votre agence pour la qualité de ses services, mais je dois dire que ce voyage n'a pas répondu à mes attentes. Je vous demande donc de bien vouloir envisager un geste commercial ou un remboursement partiel pour compenser ces désagréments.\n\nDans l'attente de votre réponse, je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.\n\nelite tcf canada\nDossier numéro: 384DUA329"],
            ['task' => 3, 'prompt' => 'La restauration rapide', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Je suis tout à fait contre les chaînes de restauration rapide car on ne connaît pas les ingrédients qui sont utilisés dans les plats. Je pense que, dans ce genre de restaurants, la nourriture n\'est pas de bonne qualité. La consommation de ce type d\'aliments peut causer des maladies, comme cela a été montré dans le film documentaire américain « Supersize Me ». C\'est vrai qu\'il est très facile de manger des hamburgers, des sandwichs ou des frites parce que c\'est très bon marché et rapide. Mais à mon avis, il est nécessaire de faire d\'autres choix pour être en bonne santé. Marie'],
                ['title' => 'Document 2', 'content' => 'Je suis favorable à la restauration rapide. Je travaille pour une chaîne de restaurants très connue et, selon moi, il est possible d\'y manger de façon équilibrée. Les menus proposent des plats complets : il y a des légumes, des salades, du pain, de la viande… C\'est le client qui est responsable de ce qu\'il consomme. S\'il choisit deux sandwichs et beaucoup de ketchup, ce n\'est pas un repas sain. De plus, les restaurants sont très propres car il y a beaucoup de normes d\'hygiène à respecter, et ce sont aussi des lieux pratiques : il est facile d\'y venir avec des enfants ou un groupe d\'amis.'],
            ], 'correction' => "Les deux documents présentent des points de vue opposés sur la restauration rapide. Dans le premier document, l'auteure critique fortement ce type de restauration qu'elle juge mauvaise pour la santé et de qualité médiocre. En revanche, le deuxième document défend la restauration rapide, considérant qu'elle peut être équilibrée si le client fait des choix raisonnables et responsables.\n\nÀ mon avis, la restauration rapide n'est pas forcément mauvaise si elle est consommée avec modération. Ces établissements offrent une solution pratique pour les personnes pressées, notamment dans les grandes villes où le rythme de vie est intense. De plus, certains restaurants proposent aujourd'hui des options plus saines, comme des salades ou des fruits. Cependant, il est important de ne pas en faire une habitude quotidienne. Manger trop souvent dans ce type de restaurant peut nuire à la santé à cause de la forte teneur en graisses, en sel et en sucre des plats. Je pense donc qu'il faut apprendre à mieux choisir ses repas et privilégier une alimentation variée. La clé réside dans l'équilibre entre plaisir, rapidité et bien-être."],
        ],
    ],
    [
        'combo' => 10,
        'tasks' => [
            ['task' => 1, 'prompt' => 'La bibliothèque de votre quartier propose une rencontre avec un(e) auteur(e). Vous souhaitez y aller avec un(e) ami(e). Vous lui écrivez un message. Vous décrivez l\'événement et vous lui proposez de venir avec vous.', 'correction' => "Salut Léa,\n\nJ'ai vu que la bibliothèque du quartier organise une rencontre avec l'écrivaine Marie Delaunay le samedi 16 novembre à 17 h. Elle viendra parler de son dernier roman Les saisons du silence, qui raconte la vie d'une femme qui décide de tout quitter pour réaliser ses rêves. Après la présentation, il y aura une séance de questions et une dédicace.\n\nJe trouve que ce serait une belle occasion de passer un moment agréable et de découvrir son univers littéraire. En plus, l'entrée est gratuite et l'ambiance promet d'être conviviale.\nSi tu es libre, ça te dirait de venir avec moi ? On pourrait y aller ensemble et prendre un café après la rencontre."],
            ['task' => 2, 'prompt' => 'Dans le cadre de la Semaine du goût, vous avez participé à une activité pour découvrir les cuisines du monde. Vous écrivez un article pour le site Internet de votre ville. Dans cet article, vous racontez votre expérience et vous expliquez ce que vous avez aimé.', 'correction' => "À la découverte des saveurs du monde\n\nChers lecteurs,\n\nDans le cadre de la Semaine du goût, j'ai eu la chance de participer à une activité culinaire organisée par le centre culturel de notre ville. Le but était de découvrir les cuisines du monde à travers différents ateliers animés par des chefs venus de divers horizons : Maroc, Japon, Italie et Mexique.\n\nJ'ai pu apprendre à préparer des plats typiques comme le couscous marocain, les sushis japonais et les tacos mexicains. Chaque chef expliquait non seulement les recettes, mais aussi les traditions liées à ces mets. Ce que j'ai le plus aimé, c'est l'ambiance conviviale et le partage entre les participants. J'ai découvert de nouvelles saveurs, de nouvelles techniques et surtout une belle ouverture sur d'autres cultures.\n\nCette expérience m'a rappelé que la cuisine est un véritable langage universel qui unit les gens au-delà des frontières."],
            ['task' => 3, 'prompt' => 'L\'art urbain : Pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Dans les grandes villes, il y a de plus en plus de peintures et de dessins sur les murs des maisons, des écoles et même des églises. Cet art urbain permet à la culture d\'avoir une place dans l\'espace public. Selon certains maires, il est important que les villes aident les artistes en leur proposant des espaces où ils sont autorisés à peindre. De plus, ces graffitis attirent les touristes qui peuvent participer à des visites thématiques sur cet art. Ils peuvent ainsi découvrir des lieux moins connus du grand public.'],
                ['title' => 'Document 2', 'content' => 'Certaines villes dépensent chaque année une somme d\'argent importante pour lutter contre les peintures de rue. Ces dessins sur les murs, sur les bancs ou dans les stations de métro sont difficiles à enlever. Il est parfois nécessaire de faire appel à des équipes de nettoyage spécialisées. Pour certains habitants, ces peintures donnent une mauvaise image de leurs quartiers. Elles provoquent aussi la colère des propriétaires des murs qui sont parfois obligés de les nettoyer eux-mêmes. Cependant, malgré les interdictions des mairies et les amendes, les graffitis continuent d\'apparaître sur les murs des villes.'],
            ], 'correction' => "Les deux documents présentent des points de vue opposés sur l'art urbain. Dans le premier document, cet art est perçu comme une forme d'expression culturelle qui embellit les villes et attire les touristes. En revanche, le deuxième document souligne les problèmes qu'il engendre : dégradations, coûts de nettoyage élevés et mécontentement des habitants.\n\nÀ mon avis, l'art urbain mérite d'être reconnu comme une véritable forme d'art lorsqu'il est encadré et réalisé dans des espaces autorisés. Il permet aux artistes de s'exprimer librement et de rendre la ville plus vivante et colorée. Les fresques murales, par exemple, peuvent valoriser certains quartiers et attirer les visiteurs. Cependant, il faut distinguer les œuvres artistiques des simples graffitis sauvages qui abîment les murs et donnent une image négative des lieux. Je pense donc qu'il est essentiel de créer davantage d'espaces dédiés à l'art urbain afin de concilier liberté artistique et respect de l'espace public. Cela encouragerait la créativité tout en préservant la propreté et l'esthétique des villes."],
        ],
    ],
    [
        'combo' => 11,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous venez de vous installer dans un nouveau logement. Vous recherchez un colocataire. Vous écrivez une annonce avec toutes les informations utiles sur le logement (lieu, taille, loyer, etc.) et vous décrivez la personne avec laquelle vous pourriez vivre (caractère, mode de vie, etc.)', 'correction' => "Colocation à louer dans un logement spacieux et confortable\n\nJe viens de m'installer dans un bel appartement situé au centre-ville de Montréal, à proximité des transports en commun, des commerces et des universités. Le logement fait 85 m², avec deux chambres lumineuses, un grand salon, une cuisine équipée (four, lave-vaisselle, micro-ondes), une salle de bain moderne et un balcon avec une belle vue sur le parc.\n\nLe loyer est de 850 $ par mois, toutes charges comprises (électricité, chauffage, Wi-Fi). La chambre disponible est meublée avec un lit double, une armoire et un bureau.\n\nJe recherche un(e) colocataire calme, respectueux(se) et sociable, aimant la propreté et la vie en communauté. J'aimerais partager le logement avec quelqu'un de responsable, non-fumeur, qui apprécie les échanges mais aussi les moments de tranquillité. Les étudiants ou jeunes professionnels sont les bienvenus."],
            ['task' => 2, 'prompt' => 'Vous avez commencé une nouvelle activité de loisir (danse, peinture, sport, etc.). Vous écrivez un message à vos amis pour raconter votre expérience et pour donner votre opinion sur cette activité.', 'correction' => "Salut les amis !\n\nJe voulais vous parler de ma nouvelle activité de loisir : j'ai commencé la danse contemporaine il y a quelques semaines, et c'est une expérience incroyable ! Au début, j'étais un peu maladroit, mais l'ambiance du cours est vraiment agréable. Les autres participants sont très accueillants et le professeur explique chaque mouvement avec patience et bonne humeur.\n\nCette activité m'a permis de découvrir une nouvelle façon de m'exprimer. À travers la danse, je ressens une liberté totale : je relâche le stress, je me détends et j'améliore en même temps ma condition physique. C'est un excellent équilibre entre art et sport.\n\nJe trouve que cette activité apporte beaucoup d'énergie positive. Franchement, je la recommande à tout le monde, surtout à ceux qui veulent bouger, se sentir bien et partager un bon moment dans une ambiance conviviale."],
            ['task' => 3, 'prompt' => 'La gratuité des musées : Pour ou contre ?', 'documents' => [
                ['title' => 'Document 1', 'content' => 'La gratuité est l\'une des valeurs fondatrices du musée, elle fait référence à l\'idéal de partage de la culture. Tous les professionnels de la culture sont d\'accord pour aller vers une démocratisation culturelle et donc réduire les obstacles à la visite d\'un musée. À la différence du théâtre ou de l\'opéra, il y a une tradition de gratuité depuis la création des musées : un dimanche par mois, l\'entrée dans les musées nationaux est gratuite pour tout le monde. Cette mesure a pour objectif d\'attirer de nouveaux visiteurs. En effet, le musée est avant tout un lieu d\'éducation qui doit accueillir le plus grand nombre. (D\'après https://www.ouest-france.fr)'],
                ['title' => 'Document 2', 'content' => 'La gratuité totale dans les musées est une fausse bonne idée car elle fait croire au public que la culture est gratuite. Or les musées ont besoin d\'un financement pour entretenir et développer leurs collections. Par contre, la mise en place de prix réduits pour des publics choisis est une solution plus adaptée. Pour que ce dispositif soit efficace, il faut accompagner les catégories de visiteurs auxquelles s\'adressent les réductions, comme par exemple organiser des visites pour les adolescents ou les personnes à mobilité réduite. Ouvrir les portes du musée ne suffit pas : il faut créer une relation active entre le musée et ses publics grâce à des activités spécifiques. (D\'après https://www.lesechos.fr)'],
            ], 'correction' => "Les deux documents présentent des points de vue opposés sur la gratuité des musées. Dans le premier document, la gratuité est vue comme un moyen de démocratiser la culture et de permettre à tous d'accéder à l'art. En revanche, le deuxième document met en avant les limites de cette mesure, soulignant que les musées ont besoin de financements pour fonctionner et que la gratuité totale n'est pas toujours la meilleure solution.\n\nÀ mon avis, la gratuité des musées est une idée positive si elle est bien encadrée. Elle permet de rendre la culture accessible à tous, surtout aux jeunes ou aux familles modestes. Cependant, il faut aussi penser à la survie économique des musées, qui ont besoin d'argent pour entretenir leurs collections et organiser des expositions. Une solution équilibrée serait de rendre les musées gratuits certains jours ou pour certaines catégories de visiteurs, tout en maintenant un tarif raisonnable pour les autres. Cela encouragerait la découverte culturelle sans compromettre la qualité des services offerts. La culture doit être partagée, mais de façon durable et responsable."],
        ],
    ],
    [
        'combo' => 12,
        'tasks' => [
            ['task' => 1, 'prompt' => 'Vous allez déménager. Des amis ont accepté de vous aider. Vous leur écrivez un message collectif pour leur expliquer comment le déménagement va se passer (lieux, horaires, durée, trajet, tâches à faire, etc.)', 'correction' => "Objet : Déménagement – Merci pour votre aide !\n\nSalut les amis,\nMerci encore de m'aider pour le déménagement ! Rendez-vous samedi à 9 h devant mon ancien appartement, 12 rue des Lilas. Nous chargerons les cartons jusqu'à midi, puis pause déjeuner (pizza offerte).\nEnsuite, direction le nouveau logement au 25 avenue du Parc — le trajet dure environ 20 minutes.\nSur place, il faudra surtout décharger les meubles et installer les cartons dans les bonnes pièces.\nJe compte sur votre bonne humeur et vos bras musclés !\nMerci d'avance, à samedi !\nelite tcf canada"],
            ['task' => 2, 'prompt' => 'Participez à notre concours pour gagner un séjour pour deux personnes dans la ville de votre choix. Rédigez un article sur le thème : « La vie de mon artiste préféré(e) ». Vous participez à ce concours. Vous expliquez pourquoi vous avez choisi cet(te) artiste et vous racontez sa vie.', 'correction' => "La vie de mon artiste préférée : Edith Piaf\n\nChers lecteurs,\n\nJ'ai choisi Édith Piaf, car elle incarne à mes yeux la force, la passion et le courage face aux difficultés de la vie. Née à Paris en 1915 dans une famille très pauvre, elle a connu une enfance difficile. Abandonnée par sa mère, elle est élevée par sa grand-mère, puis commence très jeune à chanter dans les rues pour survivre.\nDécouverte par un directeur de cabaret, elle devient rapidement célèbre grâce à sa voix puissante et à l'émotion de ses chansons. Parmi ses titres les plus connus, on trouve La Vie en rose, Hymne à l'amour et Non, je ne regrette rien.\nSa vie fut marquée par des drames personnels et des problèmes de santé, mais elle continua à chanter jusqu'à la fin. Édith Piaf reste aujourd'hui une véritable légende de la chanson française et une source d'inspiration pour des générations d'artistes.\n\nelite tcf canada"],
            ['task' => 3, 'prompt' => 'Les objets connectés', 'documents' => [
                ['title' => 'Document 1', 'content' => 'Les objets connectés facilitent notre vie quotidienne. Ce sont des objets ou des équipements pilotés à distance à l\'aide d\'un téléphone portable ou par Internet, comme le système de chauffage ou la fermeture des portes. De plus, avec une montre ou un bracelet connecté, toutes nos activités peuvent être analysées. Un logiciel va mesurer le nombre de nos pas pour nous inciter à faire davantage d\'exercice. Un domaine où l\'on comprend mieux leur utilité est celui de la surveillance de la santé. Certains objets agissent comme un carnet de santé, toujours prêts à vous rappeler un rendez-vous chez le médecin ou des médicaments à prendre.'],
                ['title' => 'Document 2', 'content' => 'Il y aurait 50 milliards d\'objets connectés dans le monde : l\'alarme, le téléviseur, la caméra de surveillance, les volets, le détecteur de fumée, etc. Face à cette évolution, la question de la sécurité se pose. En effet, un pirate informatique peut prendre le contrôle d\'un objet connecté en quelques minutes. Ou encore, un cambrioleur pourrait vérifier grâce aux caméras de surveillance connectées d\'une habitation si les occupants sont absents. Il est aussi possible d\'entrer dans le système connecté d\'une voiture et d\'en prendre les commandes à distance.'],
            ], 'correction' => "Les objets connectés prennent une place croissante dans nos vies. Dans le premier document, ils sont présentés comme des outils pratiques qui facilitent la vie quotidienne, notamment dans la santé et le bien-être. Tandis que dans le deuxième document, l'accent est mis sur les risques liés à leur utilisation, comme les problèmes de sécurité et de piratage.\n\nÀ mon avis, les objets connectés représentent une avancée technologique majeure qui transforme notre manière de vivre. Ils permettent un confort indéniable : on peut surveiller sa santé, contrôler sa maison à distance ou encore gagner du temps dans les tâches domestiques. Cependant, cette dépendance à la technologie comporte des dangers. Les données personnelles peuvent être piratées, et la vie privée est menacée. De plus, ces outils peuvent rendre certaines personnes moins actives ou trop dépendantes. À mon sens, il est donc essentiel de trouver un équilibre : profiter des avantages de ces technologies tout en restant vigilant face à leurs limites et en renforçant la sécurité numérique."],
        ],
    ],
];
